import type { ModuleSpecs } from "../types";

/** Module 31 — Manufacturing Execution System (MES). */

const ITEM = "item|Item|enum|@items";
const WC = "wc|Work Center|enum|Press-01;Press-02;Press-03;Polish-01;Plating-A;Plating-B;Assembly-1;Assembly-2";
const OPERATOR = "operator|Operator|person";
const SUPERVISOR = "supervisor|Supervisor|person";
const SHIFT = "shift|Shift|enum|A (06–14);B (14–22);C (22–06)";
const ORDER = "order|Work Order|enum|WO-26-1042;WO-26-1051;WO-26-1063;WO-26-1078;WO-26-1090;WO-26-1104";

export const MES: ModuleSpecs = {
  "shop-floor": {
    name: "Shop Floor Control",
    kind: "overview",
    summary: "Live status of every work centre",
    entity: "Floor Job",
    ref: "SFJ",
    fields: [
      ITEM,
      WC,
      ORDER,
      "planned|Planned Qty|int|8000;140000;pcs",
      "produced|Produced Qty|int|1200;138000;pcs",
      "oee|OEE|pct|48;96",
      SUPERVISOR,
      SHIFT,
      "date|Job Date|date|-18;2",
    ],
    statuses: ["Running", "Setup", "Idle", "Breakdown", "Completed"],
    measure: "produced",
    insight:
      "Press-02 has been in setup for three consecutive shifts — changeover time is the biggest single loss on the floor this week.",
    rows: 48,
  },

  "job-dispatch": {
    name: "Job Dispatch",
    kind: "board",
    summary: "Release work to the lines",
    entity: "Dispatch Job",
    ref: "DSP",
    fields: [
      ITEM,
      WC,
      ORDER,
      "qty|Dispatch Qty|int|5000;120000;pcs",
      "priority|Priority|enum|Urgent;High;Normal;Filler",
      SUPERVISOR,
      SHIFT,
      "release|Release Date|date|-10;14",
    ],
    statuses: ["Queued", "Released", "In Progress", "Paused", "Completed"],
    measure: "qty",
  },

  "machine-status": {
    name: "Machine Status",
    kind: "analytics",
    summary: "Run, idle and down states",
    entity: "Machine State",
    ref: "MST",
    fields: [
      "machine|Machine|enum|Power Press 60T;Power Press 110T;Hydraulic Press 150T;Vibratory Polisher;Barrel Plating Line;Rack Plating Line;Auto Assembly Cell",
      WC,
      "runtime|Run Hours|float|0;24;hrs;1",
      "idle|Idle Hours|float|0;8;hrs;1",
      "availability|Availability|pct|55;99",
      OPERATOR,
      SHIFT,
      "date|State Date|date|-14;0",
    ],
    statuses: ["Running", "Idle", "Setup", "Breakdown", "Offline"],
    measure: "runtime",
  },

  oee: {
    name: "OEE Monitor",
    kind: "analytics",
    summary: "Availability × performance × quality",
    entity: "OEE Reading",
    ref: "OEE",
    fields: [
      "machine|Machine|enum|Power Press 60T;Power Press 110T;Hydraulic Press 150T;Vibratory Polisher;Barrel Plating Line;Auto Assembly Cell",
      "availability|Availability|pct|62;99",
      "performance|Performance|pct|58;98",
      "quality|Quality|pct|88;99",
      "oee|OEE|pct|45;92",
      SHIFT,
      SUPERVISOR,
      "date|Reading Date|date|-21;0",
    ],
    statuses: ["World Class", "On Target", "Below Target", "Critical"],
    measure: "oee",
  },

  downtime: {
    name: "Downtime Capture",
    kind: "list",
    summary: "Stop reasons and lost minutes",
    entity: "Downtime Event",
    ref: "DWN",
    fields: [
      "machine|Machine|enum|Power Press 60T;Power Press 110T;Hydraulic Press 150T;Vibratory Polisher;Barrel Plating Line;Auto Assembly Cell",
      "reason|Reason|enum|Die change;Tool breakage;Material shortage;Power failure;Operator absent;Quality hold;Preventive maintenance;Air pressure drop",
      "minutes|Lost Minutes|int|10;480;min",
      "category|Category|enum|Planned;Unplanned;External",
      OPERATOR,
      SHIFT,
      "date|Event Date|date|-30;0",
    ],
    statuses: ["Open", "Under Review", "Root Cause Found", "Closed"],
    measure: "minutes",
  },

  "operator-terminal": {
    name: "Operator Terminal",
    kind: "form",
    summary: "Shop-floor data entry",
    entity: "Terminal Entry",
    ref: "TRM",
    fields: [
      ORDER,
      ITEM,
      WC,
      "goodQty|Good Qty|int|500;40000;pcs",
      "rejectQty|Reject Qty|int|0;900;pcs",
      OPERATOR,
      SHIFT,
      "date|Entry Date|date|-6;0",
    ],
    statuses: ["Draft", "Submitted", "Verified", "Posted", "Rejected"],
    measure: "goodQty",
  },

  "production-feedback": {
    name: "Production Feedback",
    kind: "list",
    summary: "Operation confirmations from the line",
    entity: "Confirmation",
    ref: "CNF",
    fields: [
      ORDER,
      "operation|Operation|enum|Blanking;Forming;Deburring;Polishing;Plating;Assembly;Inspection;Packing",
      WC,
      "qty|Confirmed Qty|int|800;90000;pcs",
      "scrap|Scrap Qty|int|0;1800;pcs",
      "hours|Manhours|float|0.5;16;hrs;1",
      OPERATOR,
      "date|Confirmed On|date|-25;0",
    ],
    statuses: ["Pending", "Confirmed", "Adjusted", "Reversed"],
    measure: "qty",
  },

  andon: {
    name: "Andon Board",
    kind: "overview",
    summary: "Escalation signals from the floor",
    entity: "Andon Call",
    ref: "AND",
    fields: [
      WC,
      "signal|Signal|enum|Material call;Quality issue;Machine fault;Tool change;Supervisor call;Safety stop",
      "responseMin|Response Time|int|1;95;min",
      "severity|Severity|enum|Critical;High;Medium;Low",
      OPERATOR,
      SHIFT,
      "date|Raised On|date|-12;0",
    ],
    statuses: ["Raised", "Acknowledged", "Attending", "Resolved", "Escalated"],
    measure: "responseMin",
  },

  "cycle-monitor": {
    name: "Cycle Time Monitor",
    kind: "analytics",
    summary: "Actual cycle against standard",
    entity: "Cycle Reading",
    ref: "CYC",
    fields: [
      ITEM,
      "operation|Operation|enum|Blanking;Forming;Deburring;Polishing;Plating;Assembly;Inspection",
      WC,
      "standard|Standard Cycle|float|0.4;9;sec;2",
      "actual|Actual Cycle|float|0.4;12;sec;2",
      "variance|Variance|pct|60;135",
      OPERATOR,
      "date|Measured On|date|-20;0",
    ],
    statuses: ["Within Standard", "Marginal", "Above Standard", "Under Study"],
    measure: "actual",
  },

  "shift-handover": {
    name: "Shift Handover",
    kind: "form",
    summary: "Shift-to-shift notes and open points",
    entity: "Handover Note",
    ref: "HOV",
    fields: [
      SHIFT,
      WC,
      "outgoing|Outgoing Supervisor|person",
      "incoming|Incoming Supervisor|person",
      "openPoints|Open Points|int|0;12",
      "output|Shift Output|int|4000;120000;pcs",
      "date|Handover Date|date|-15;0",
    ],
    statuses: ["Draft", "Submitted", "Acknowledged", "Closed"],
    measure: "output",
  },

  "labor-tracking": {
    name: "Labour Tracking",
    kind: "analytics",
    summary: "Manhours booked against each job",
    entity: "Labour Booking",
    ref: "LAB",
    fields: [
      ORDER,
      WC,
      OPERATOR,
      "hours|Booked Hours|float|1;12;hrs;1",
      "earned|Earned Hours|float|0.5;13;hrs;1",
      "efficiency|Efficiency|pct|52;128",
      SHIFT,
      "date|Booking Date|date|-28;0",
    ],
    statuses: ["Open", "Approved", "Posted", "Disputed"],
    measure: "hours",
  },

  "work-instructions": {
    name: "Digital Work Instructions",
    kind: "list",
    summary: "Illustrated SOPs at the station",
    entity: "Work Instruction",
    ref: "DWI",
    fields: [
      ITEM,
      "operation|Operation|enum|Blanking;Forming;Deburring;Polishing;Plating;Assembly;Inspection;Packing",
      WC,
      "version|Version|enum|Rev A;Rev B;Rev C;Rev D",
      "views|Station Views|int|12;2400",
      "author|Author|person",
      "date|Effective From|date|-240;20",
    ],
    statuses: ["Draft", "In Review", "Released", "Superseded", "Withdrawn"],
    measure: "views",
  },

  "traceability-log": {
    name: "Batch Traceability Log",
    kind: "list",
    summary: "Heat lot to finished carton",
    entity: "Trace Record",
    ref: "TRC",
    fields: [
      ITEM,
      "heatLot|Heat Lot|enum|HL-4471;HL-4489;HL-4502;HL-4517;HL-4530;HL-4548",
      ORDER,
      WC,
      "qty|Traced Qty|int|2000;90000;pcs",
      "carton|Carton Range|enum|CTN-001-040;CTN-041-090;CTN-091-150;CTN-151-220",
      "date|Captured On|date|-45;0",
    ],
    statuses: ["Captured", "Verified", "Linked", "Exception"],
    measure: "qty",
  },

  "material-consumption": {
    name: "Material Consumption",
    kind: "list",
    summary: "Issued against standard usage",
    entity: "Consumption Entry",
    ref: "MCN",
    fields: [
      ORDER,
      "material|Material|enum|Brass Strip 0.8mm;Brass Strip 1.2mm;Zinc Alloy Ingot;Steel Wire 2.0mm;Nickel Anode;Copper Anode",
      "issued|Issued Qty|float|20;1800;kg;1",
      "standard|Standard Qty|float|18;1750;kg;1",
      "variance|Usage Variance|pct|82;124",
      WC,
      "date|Issue Date|date|-30;0",
    ],
    statuses: ["Within Norm", "Over Consumption", "Under Review", "Adjusted"],
    measure: "issued",
  },

  "quality-hold": {
    name: "Quality Hold",
    kind: "board",
    summary: "Lots stopped on the line",
    entity: "Hold Lot",
    ref: "QHD",
    fields: [
      ITEM,
      ORDER,
      WC,
      "qty|Held Qty|int|500;60000;pcs",
      "defect|Defect|enum|Plating stain;Dimension out;Burr;Colour mismatch;Deformation;Contamination",
      "inspector|Inspector|person",
      "date|Held On|date|-20;0",
    ],
    statuses: ["On Hold", "Under Review", "Rework Advised", "Released", "Scrapped"],
    measure: "qty",
  },

  changeover: {
    name: "Changeover Schedule",
    kind: "calendar",
    summary: "Planned die and tooling changes",
    entity: "Changeover",
    ref: "CHG",
    fields: [
      WC,
      "fromItem|From Item|enum|@items",
      "toItem|To Item|enum|@items",
      "setupMin|Setup Minutes|int|20;240;min",
      "die|Die|enum|DIE-1102;DIE-1148;DIE-1176;DIE-1209;DIE-1233",
      SUPERVISOR,
      "date|Planned Date|date|-8;25",
    ],
    statuses: ["Planned", "In Progress", "Completed", "Delayed"],
    measure: "setupMin",
  },

  "tooling-usage": {
    name: "Tooling Usage",
    kind: "list",
    summary: "Strokes consumed per tool on the floor",
    entity: "Tool Usage",
    ref: "TUS",
    fields: [
      "tool|Tool|enum|Blanking Die 15mm;Forming Punch 17L;Trim Die 9mm;Coining Die 20L;Piercing Punch 4mm",
      WC,
      ORDER,
      "strokes|Strokes Used|int|4000;480000",
      "life|Rated Life|int|200000;900000",
      "wear|Life Consumed|pct|8;98",
      "date|Recorded On|date|-30;0",
    ],
    statuses: ["Healthy", "Monitor", "Near End of Life", "Withdrawn"],
    measure: "strokes",
  },

  "energy-per-machine": {
    name: "Machine Energy Draw",
    kind: "analytics",
    summary: "kWh consumed by work centre",
    entity: "Energy Reading",
    ref: "MEN",
    fields: [
      "machine|Machine|enum|Power Press 60T;Power Press 110T;Hydraulic Press 150T;Vibratory Polisher;Barrel Plating Line;Rack Plating Line",
      WC,
      "kwh|Energy|float|40;1400;kWh;1",
      "output|Output|int|4000;120000;pcs",
      "intensity|kWh / 1000 pcs|float|1.2;18;kWh;2",
      SHIFT,
      "date|Reading Date|date|-30;0",
    ],
    statuses: ["Normal", "Above Baseline", "Peak Draw", "Under Review"],
    measure: "kwh",
  },

  "mes-alerts": {
    name: "MES Alerts",
    kind: "list",
    summary: "Threshold breaches raised by the system",
    entity: "Alert",
    ref: "ALT",
    fields: [
      "alert|Alert Type|enum|Cycle time drift;OEE below target;Downtime threshold;Scrap spike;Tool life exceeded;Missing confirmation",
      WC,
      "severity|Severity|enum|Critical;High;Medium;Low",
      "ageHrs|Open For|int|1;72;hrs",
      SUPERVISOR,
      "date|Raised On|date|-14;0",
    ],
    statuses: ["New", "Acknowledged", "In Progress", "Resolved", "Suppressed"],
    measure: "ageHrs",
  },

  "terminal-config": {
    name: "Terminal Configuration",
    kind: "settings",
    summary: "Station behaviour and data capture rules",
    entity: "Terminal",
    ref: "TCF",
    fields: [
      "terminal|Terminal|enum|TERM-PRESS-01;TERM-PRESS-02;TERM-POLISH-01;TERM-PLATE-A;TERM-ASSY-01",
      WC,
      "mode|Capture Mode|enum|Scan only;Scan + keypad;Auto from PLC;Manual",
      "interval|Poll Interval|int|5;120;sec",
      "uptime|Terminal Uptime|pct|82;100",
      SUPERVISOR,
      "date|Last Configured|date|-90;0",
    ],
    statuses: ["Active", "Standby", "Maintenance", "Retired"],
    measure: "uptime",
    settings: [
      "Require scan before confirmation",
      "Block entry beyond planned quantity",
      "Auto-raise Andon on cycle overrun",
    ],
  },
};
