import type { ModuleSpecs } from "../types";

/**
 * Module 10 — Proforma Invoice (PI) Management.
 *
 * Fifty-one workspaces in the master serial order, from the PI dashboard and
 * AI-assisted PO import through the PI document itself, its masters, commercial
 * and shipping terms, approval, amendment and version control, and on to the
 * compliance, reporting, intelligence and system surfaces that sit on top.
 *
 * Each workspace carries the whole feature list of its serial entry: the data
 * points become fields, the lifecycle becomes statuses, and the behavioural
 * options become configuration toggles the workspace can actually hold.
 */

/* ── Shared field fragments ────────────────────────────────────────────── */

const BUYER = "buyer|Buyer|enum|@buyers";
const ITEM = "item|Item|enum|@items";
const EXEC = "executive|Marketing Person|person";
const COMMERCIAL = "commercial|Commercial Person|person";
const CURRENCY = "currency|Currency|enum|USD;EUR;GBP;JPY;CNY;CAD;AUD;CHF";
const PI_LINK = "piNo|PI Number|enum|PI-2026-000125;PI-2026-000131;PI-2026-000148;PI-2026-000156;PI-2026-000172;PI-2026-000188;PI-2026-000204;PI-2026-000219";
const STYLE = "style|Style|enum|ST.J20143D;SM-DENIM-1180;SM-TRIM-2240;SM-BTN-3310;SM-ZIP-4420;SM-RVT-5150;SM-EYE-6280;SM-BKL-7360";
const BUYER_STYLE = "buyerStyle|Buyer Style|enum|HM-24471;ZR-8802;LS-511X;PR-3390;UQ-7712;DC-4408;CA-9931";
const COLOR = "color|Colour|enum|YKK-233;Antique Brass;Gunmetal;Matte Black;Nickel Free;Gold;Brushed Silver;Copper;White Enamel";
const SIZE = "size|Size|enum|45 CM;47 CM;48.5 CM;50.5 CM;52 CM;15mm;17mm;20L;No. 5;25mm";
const UOM = "uom|UOM|enum|Pcs;Gross;Dozen;Set;Kg;Carton;Roll";
const PAYMENT_TERM = "paymentTerms|Payment Terms|enum|Irrevocable LC at Sight;LC 30 days;LC 60 days;LC 90 days Sight;TT in advance;TT 30 days;DP at sight;DA 60 days;CAD;30% advance + 70% LC";
const COUNTRY = "country|Country|enum|Germany;United States;United Kingdom;Spain;Netherlands;Japan;China;Canada;Australia;Sweden";
const PERIOD = "period|Period|enum|Jan 2026;Feb 2026;Mar 2026;Apr 2026;May 2026;Jun 2026;Jul 2026;Aug 2026";
const HS_CODE = "hsCode|HS Code|enum|8308.10.00;8308.20.00;8308.90.00;9606.10.00;9606.22.00;9607.11.00;7326.90.00";
const INCOTERM = "incoterm|Incoterms|enum|FOB;CIF;CFR;CNF;EXW;FCA;CIP;DDP;DAP";
const POL = "pol|Port of Loading|enum|Chattogram Port, Bangladesh;Dhaka ICD;Mongla;Pangaon;Shanghai;Ningbo";
const POD = "pod|Port of Destination|enum|Hamburg Port, Germany;Rotterdam;Barcelona;Felixstowe;New York;Los Angeles;Yokohama;Vancouver";

export const PROFORMA_INVOICE: ModuleSpecs = {
  /* ── 01 ─ PI Dashboard ─────────────────────────────────────────────── */
  "pi-dashboard": {
    name: "PI Dashboard", kind: "overview", summary: "Today, monthly, pending, approved and rejected at a glance",
    entity: "PI Summary", ref: "PID",
    fields: [
      "summaryView|Summary View|enum|Dashboard overview;Buyer-wise summary;Marketing-wise summary;Country-wise summary;Currency-wise summary;PI value analysis;KPI dashboard",
      "bucket|Period Bucket|enum|Today's PI;Monthly PI;Quarterly;Year to date",
      BUYER, COUNTRY, CURRENCY, EXEC, PERIOD,
      "todayPi|Today's PI|int|0;18;PIs",
      "monthlyPi|Monthly PI|int|1;180;PIs",
      "pendingPi|Pending PI|int|0;48;PIs",
      "approvedPi|Approved PI|int|0;160;PIs",
      "rejectedPi|Rejected PI|int|0;24;PIs",
      "amendmentPending|Amendment Pending|int|0;22;PIs",
      "lcPending|LC Pending|int|0;30;PIs",
      "shipmentPending|Shipment Pending|int|0;36;PIs",
      "piValue|Total PI Value|money|4000;2400000",
      "approvalRate|Approval Rate|pct|38;100",
      "aiAlert|AI Alert|text|Three LCs expire inside 14 days;Buyer credit utilisation above 80%;Duplicate PO detected on re-import;Shipment pending beyond agreed ETD;Approval queue breaching SLA;Currency exposure rising on the EUR book;No alert raised",
      "recentActivity|Recent Activity|text|PI approved by commercial head;Amendment raised on quantity;LC advised by Basic Bank;Buyer PO imported by OCR;Shipment booked against PI;Revision restored to previous version",
      "date|Period End|date|-330;0",
    ],
    statuses: ["Approved", "Pending Approval", "Under Review", "Draft", "Rejected"],
    measure: "piValue", rows: 58,
    insight: "62% of PI value sits with four buyers and 78% of it is raised in USD — the EUR book carries the currency exposure but only 11% of the volume.",
    settings: [
      "Show the charts and graphs band above the dashboard tables",
      "Pin quick actions for new PI, import PO and approval queue to the header",
      "Email the dashboard report to the commercial head every Monday morning",
    ],
  },

  /* ── 02 ─ AI PO Import ─────────────────────────────────────────────── */
  "ai-po-import": {
    name: "AI PO Import", kind: "form", summary: "PDF, Excel, image and email PO into a draft PI",
    entity: "Import Job", ref: "IMP",
    fields: [
      "fileName|Source File|text|BuyerPO-4471.pdf;OrderSheet-Q2.xlsx;Scanned-PO-882.jpg;PO58125-email.eml;Trim-Order.pdf;Bulk-Upload.zip;Confirmation.docx",
      "sourceType|Import Type|enum|PDF PO import;Excel PO import;Image PO import;Email PO import;Multi-file upload",
      "ocrPages|OCR Pages Read|int|1;60;pages",
      BUYER,
      "extraction|AI Extraction|enum|Auto buyer detection;Auto style detection;Auto item detection;Auto colour & size detection;Auto quantity detection;Auto price detection;Auto currency detection;Full field extraction",
      "extractedFields|Fields Extracted|int|8;180;fields",
      "confidence|AI Extraction Confidence|pct|42;99.5",
      "duplicateCheck|Duplicate PO Detection|bool|Duplicate found;No duplicate",
      "validationFindings|Validation Findings|int|0;18",
      "autoCreated|Auto Create PI|bool|PI auto-created;Held for review",
      "piCreated|Created PI|enum|PI-2026-000125;PI-2026-000131;PI-2026-000148;PI-2026-000156;Not created yet",
      "errorLog|Error Log|text|Quantity column unreadable on page 3;Currency symbol ambiguous;Buyer name not in master;Size break split across cells;Price field blank;No errors logged",
      "uploadedBy|Uploaded By|person",
      "date|Imported On|date|-300;0",
    ],
    statuses: ["PI Created", "Extracted", "Extracting", "Awaiting Review", "Duplicate Held", "Validation Failed"],
    measure: "extractedFields", rows: 56,
    insight: "Native PDF and Excel imports clear validation 94% of the time; scanned image OCR still needs a human on one job in three, almost always on handwritten quantity columns.",
    settings: [
      "Create the draft PI automatically when extraction confidence is above 95%",
      "Read PO attachments straight off the commercial mailbox without a manual upload",
      "Hold any import that matches an existing buyer PO number as a suspected duplicate",
      "Keep every uploaded source file against the import history for audit",
    ],
  },

  /* ── 03 ─ File Inquiry ─────────────────────────────────────────────── */
  "file-inquiry": {
    name: "File Inquiry", kind: "list", summary: "One file, every status from inquiry to shipment",
    entity: "Inquiry File", ref: "FIL",
    fields: [
      "fileNo|File Number|code|FIL",
      "inquiryType|Inquiry Type|enum|Buyer inquiry;Style inquiry;Brand inquiry;Season inquiry;General registration",
      BUYER, STYLE,
      "brand|Brand|enum|H&M;Zara;Levi's;Primark;Uniqlo;Decathlon;C&A;Bestseller",
      "season|Season|enum|SS26;AW26;SS27;AW27;Basic carry-over",
      "orderStatus|Order Status|enum|Order confirmed;Order pending;Order lost;Not yet ordered",
      "costingStatus|Costing Status|enum|Costing approved;Costing in progress;Costing revised;Not costed",
      "sampleStatus|Sample Status|enum|Sample approved;Sample submitted;Sample in development;Sample rejected;No sample",
      "quotationStatus|Quotation Status|enum|Quotation accepted;Quotation sent;Quotation revised;Not quoted",
      "poStatus|PO Status|enum|PO received;PO awaited;PO cancelled;PO partial",
      "piStatus|PI Status|enum|PI approved;PI raised;PI draft;PI not raised",
      "tnaStatus|TNA Status|enum|On schedule;At risk;Delayed;Completed;Not planned",
      "shipmentStatus|Shipment Status|enum|Shipped;Booked;Planned;Not planned;Delayed",
      "timelineDays|Timeline Age|int|1;280;days",
      "documents|Document Attachments|int|0;24;files",
      "aiAnalysis|AI File Analysis|text|Costing lagging the sample approval by three weeks;Quotation accepted but PO never followed;TNA slipping on the plating stage;File ready to convert into a PI;Buyer has gone quiet since the last quotation;Healthy file - no action needed",
      "value|Inquiry Value|money|4000;2400000",
      EXEC,
      "date|Registered On|date|-330;0",
    ],
    statuses: ["Converted to PI", "Active", "Quoted", "Registered", "On Hold", "Lost"],
    measure: "value", rows: 60,
    insight: "Files that reach quotation inside three weeks convert at more than double the rate of those that do not — the costing stage, not the buyer, is what usually holds them.",
    settings: [
      "Open a file automatically when a new buyer inquiry is registered",
      "Show the full inquiry to shipment timeline on the file detail view",
      "Warn when a file has sat at the same status for more than 21 days",
    ],
  },

  /* ── 04 ─ Export PI Entry ──────────────────────────────────────────── */
  "export-pi-entry": {
    name: "Export PI Entry", kind: "form", summary: "Raise a proforma invoice end to end",
    entity: "Proforma Invoice", ref: "PI",
    fields: [
      "piNumber|PI Number|code|PI",
      "revisionNo|Revision No|enum|00;01;02;03;04",
      BUYER,
      "buyerName|Buyer Name|enum|ZIZZI;BIG BOSS;H&M;ZARA;LEVI'S;PRIMARK;UNIQLO",
      "buyerAddress|Buyer Address|text|Aptech Industrial Park Holding No 30 Sarabo Kashimpur Gazipur;Master Samuelsgatan 46 Stockholm;Avenida Diputacion Arteixo;1155 Battery Street San Francisco;Neuer Wall 12 Hamburg",
      "seller|Seller / Beneficiary|enum|Smart Metal Accessories Ltd.;Smart Metal Export FZE;Smart Trims BD Ltd.",
      EXEC, COMMERCIAL, PAYMENT_TERM, CURRENCY,
      "lcNo|LC Number|enum|LC-2026-4471;LC-2026-4488;LC-2026-4502;LC-2026-4519;LC to be opened",
      "bank|Bank Information|enum|Basic Bank Limited;Standard Chartered Bangladesh;HSBC Bangladesh;Eastern Bank PLC;City Bank PLC",
      "shipmentMode|Shipment Mode|enum|Sea Freight FCL;Sea Freight LCL;Air Freight;Courier;Multimodal",
      POL, POD, INCOTERM,
      STYLE, ITEM, COLOR, SIZE, UOM,
      "quantity|Total Quantity|int|50;2400000;Pcs",
      "unitPrice|Unit Price|float|0.02;4.8;USD;4",
      "fobValue|Total FOB Value|money|100;2400000",
      "freight|Freight|money|0;180000",
      "insurance|Insurance|money|0;48000",
      "packingCost|Packing Cost|money|0;98000",
      "otherCharges|Other Charges|money|0;68000",
      "grandTotal|Grand Total|money|100;2800000",
      "documentsAttached|Documents Attached|int|0;12;files",
      "terms|Terms & Conditions|enum|Standard export terms;Buyer specific terms;LC submission terms;Custom clause set",
      "remarks|Remarks|text|FOLLOW MZS# 11563 - REVISE BCOZ PULLER NUMBER ADDED;Sample approved before bulk;Nickel-free certificate required;Split shipment agreed;Buyer inspection at factory;Standard packing",
      "validUpto|Valid Upto|date|-10;120",
      "etd|ETD|date|-30;200",
      "eta|ETA|date|-20;240",
      "date|PI Date|date|-300;0",
    ],
    statuses: ["Draft", "Submitted", "Approved", "Rejected", "Cancelled"],
    measure: "grandTotal", rows: 54,
    insight: "Quantity times unit price rolls into the FOB value and the charges block rolls into the grand total, so a PI saved as a draft already carries a defensible figure for the approval queue and the printed document.",
    settings: [
      "Generate the PI number from the numbering series instead of typing it",
      "Recalculate FOB value and grand total automatically from quantity, price and charges",
      "Let AI auto-fill the buyer, bank and terms block from the last approved PI for that buyer",
      "Require submission for approval before a PI can be printed as a buyer copy",
    ],
  },

  /* ── 05 ─ PI List & Register ───────────────────────────────────────── */
  "pi-list-register": {
    name: "PI List & Register", kind: "list", summary: "Every PI, draft to cancelled, with the full register",
    entity: "PI Record", ref: "PIR",
    fields: [
      "piNumber|PI Number|code|PI",
      "revisionNo|Revision|enum|00;01;02;03",
      BUYER, CURRENCY, STYLE,
      "quantity|Quantity|int|50;2400000;Pcs",
      "totalValue|PI Value|money|4000;2400000",
      PAYMENT_TERM, EXEC,
      "approvalStatus|Approval Status|enum|Approved;Pending approval;Returned for correction;Rejected;Not submitted",
      "amendmentStatus|Amendment Status|enum|No amendment;Amendment pending;Amendment approved;Amendment rejected",
      "lifecycleAction|Last Action|enum|Created;Copied PI;Duplicated PI;Cancelled PI;Reopened PI;Printed;Exported",
      "printCount|Print Count|int|0;24;copies",
      "activityEntries|Activity History|int|1;42;entries",
      "deliveryDate|Delivery Date|date|-60;180",
      "date|PI Date|date|-330;0",
    ],
    statuses: ["Approved", "Pending", "Draft", "Cancelled", "Reopened", "Closed"],
    measure: "totalValue", rows: 70,
    insight: "The register is the single list behind every other view — filter it by buyer, date, currency or status and the print, PDF and Excel export all carry exactly the rows you filtered to.",
    settings: [
      "Carry line items, charges and attachments across when a PI is copied or duplicated",
      "Require a reason before a PI is cancelled or reopened from the register",
      "Write every print, export and bulk print action to the audit log",
    ],
  },

  /* ── 06 ─ PI Search & Advanced Search ──────────────────────────────── */
  "pi-search": {
    name: "PI Search & Advanced Search", kind: "list", summary: "Find any PI by any field, saved filter or barcode",
    entity: "Indexed PI", ref: "SRC",
    fields: [
      "piNumber|PI Number|code|PI",
      BUYER, STYLE, ITEM, CURRENCY, COUNTRY, EXEC,
      "poNo|PO Number|enum|PO58125;PO58140;PO58166;PO58191;PO58204;PO58233",
      "fileNo|File Number|enum|FIL-26-1041;FIL-26-1053;FIL-26-1067;FIL-26-1082;FIL-26-1096",
      "lcNo|LC Number|enum|LC-2026-4471;LC-2026-4488;LC-2026-4502;LC-2026-4519;LC-2026-4533",
      "shipmentRef|Shipment Reference|enum|SHP-26-2201;SHP-26-2214;SHP-26-2238;SHP-26-2255;Not shipped",
      "totalValue|PI Value|money|4000;2400000",
      "searchMode|Search Mode|enum|PI no search;Buyer search;PO search;File search;Style search;LC search;Marketing search;Date range search;Status search;Country search;Currency search;Shipment search;Amount search;Advanced filter;Smart search;AI search;Barcode search;Voice search",
      "savedFilter|Saved Filter|enum|My pending approvals;This month EUR book;Key accounts above 100k;LC expiring soon;Unshipped approved PIs;No saved filter",
      "matchCount|Results Matched|int|1;480;rows",
      "date|PI Date|date|-360;0",
    ],
    statuses: ["Approved", "Pending", "Draft", "Cancelled", "Closed"],
    measure: "totalValue", rows: 72,
    insight: "Search runs across every column at once — type a buyer, a style code, a PO or a PI number and the register narrows live, then save the filter so the same question answers itself next month.",
    settings: [
      "Search every column at once rather than only the PI number",
      "Keep saved filters available to the whole marketing team, not just their author",
      "Enable barcode and voice search on the mobile layout",
      "Export the search result exactly as filtered and sorted on screen",
    ],
  },

  /* ── 07 ─ Export PI (Production) ───────────────────────────────────── */
  "export-pi-production": {
    name: "Export PI (Production)", kind: "list", summary: "Factory, line, material and delivery against a PI",
    entity: "Production PI", ref: "PPI",
    fields: [
      PI_LINK, BUYER, STYLE, ITEM,
      "factory|Factory Allocation|enum|Gazipur Plant;Chattogram Unit;Narayanganj Unit;Ho Chi Minh Plant;Subcontract partner",
      "line|Line Allocation|enum|Press-01;Press-02;Press-03;Plating-A;Plating-B;Assembly-1;Assembly-2;Packing-1",
      "orderQty|Order Quantity|int|50;2400000;Pcs",
      "productionQty|Production Quantity|int|0;2400000;Pcs",
      "balanceQty|Balance Quantity|int|0;980000;Pcs",
      "materialAllocated|Material Allocation|pct|0;100",
      "bomRef|BOM Link|enum|BOM-26-1104;BOM-26-1127;BOM-26-1148;BOM-26-1163;BOM not linked",
      "splitAction|Split / Merge|enum|Full PI;Partial PI;Split PI - part 1;Split PI - part 2;Merged PI",
      "shipmentRef|Shipment Link|enum|SHP-26-2201;SHP-26-2214;SHP-26-2238;SHP-26-2255;Not booked",
      "aiPlanNote|AI Production Planning|text|Move to Press-02 to clear the plating bottleneck;Split into two deliveries to hold the ETD;Material short by 4 days - pull forward the PO;Capacity available - merge with the next PI;Plan is achievable as scheduled",
      "completion|Production Progress|pct|0;100",
      "scheduleStart|Production Schedule|date|-90;120",
      "deliveryPlan|Delivery Plan|date|-40;200",
      "date|Released On|date|-300;0",
    ],
    statuses: ["Completed", "In Production", "Material Allocated", "Planned", "On Hold", "Delayed"],
    measure: "productionQty", rows: 60,
    insight: "Balance quantity, not order quantity, is what the shipping desk works from — a PI split across two sailings shows both parts here with their own line and delivery plan.",
    settings: [
      "Allocate material against the BOM automatically when a production PI is released",
      "Block a shipment link until the production quantity covers the booked carton count",
      "Let AI propose the line allocation from current capacity before a planner confirms it",
    ],
  },

  /* ── 08 ─ LC Information ───────────────────────────────────────────── */
  "lc-information": {
    name: "LC Information", kind: "list", summary: "Letters of credit, amendment, expiry and linking",
    entity: "Letter of Credit", ref: "LC",
    fields: [
      "lcNumber|LC Number|code|LC",
      BUYER, PI_LINK,
      "lcValue|LC Value|money|20000;4800000",
      "beneficiary|Beneficiary|text|Smart Metal Accessories Ltd.;Smart Metal Export FZE;Smart Trims BD Ltd.",
      "issuingBank|Issuing Bank|enum|Deutsche Bank AG;HSBC London;BNP Paribas;Citibank NA;Bank of China;Mizuho Bank;Santander",
      "advisingBank|Advising Bank|enum|Basic Bank Limited;Standard Chartered Bangladesh;HSBC Bangladesh;Eastern Bank PLC;City Bank PLC",
      "lcTerms|LC Terms|enum|At sight;30 days sight;60 days sight;90 days sight;Usance 120 days;Confirmed at sight",
      "amendments|LC Amendments|int|0;6",
      "utilised|Utilisation|money|0;4800000",
      "balance|Balance|money|0;4800000",
      "invoiceLink|Invoice Link|enum|INV-26-3301;INV-26-3318;INV-26-3342;INV-26-3367;Not invoiced",
      "shipmentLink|Shipment Link|enum|SHP-26-2201;SHP-26-2214;SHP-26-2238;Not booked",
      "docChecklist|Document Checklist|pct|20;100",
      "aiValidation|AI Validation|text|Shipment date falls after the latest shipment allowed;HS code differs from the invoice;Partial shipment not permitted under this LC;Beneficiary name mismatch with the bank record;All clauses validate clean",
      "expiryAlert|Expiry Alert|bool|Alert raised;No alert",
      "shipmentDate|Latest Shipment Date|date|-30;180",
      "lcDate|LC Date|date|-330;0",
      "expiryDate|LC Expiry|date|-30;210",
    ],
    statuses: ["Accepted", "Advised", "Partially Utilised", "Fully Utilised", "Amended", "Expiring Soon", "Expired"],
    measure: "lcValue", rows: 54,
    insight: "Nine LCs expire inside sixty days with unutilised balance still on them. Each one needs either a shipment booked or an amendment raised before the documents lose their cover.",
    settings: [
      "Raise an expiry reminder 21 days before the latest shipment date",
      "Validate every LC against the linked PI for value, terms and shipment window",
      "Require the document checklist to be complete before documents go to the bank",
    ],
  },

  /* ── 09 ─ Bank & Currency ──────────────────────────────────────────── */
  "bank-currency": {
    name: "Bank & Currency", kind: "list", summary: "Accounts, SWIFT, exchange rate and conversion",
    entity: "Bank Account", ref: "BNK",
    fields: [
      "bank|Bank Master|enum|Basic Bank Limited;Standard Chartered Bangladesh;HSBC Bangladesh;Eastern Bank PLC;City Bank PLC;Dutch-Bangla Bank;Brac Bank;Prime Bank",
      "branch|Branch Setup|enum|Mirpur Branch Dhaka;Motijheel Corporate;Gulshan Circle 1;Agrabad Chattogram;Dhanmondi;Uttara;Karwan Bazar EPZ",
      "accountNo|Account Setup|code|AC",
      "swift|Swift Code|enum|BKSBBDDH022;SCBLBDDX;HSBCBDDH;EBLDBDDH;CIBLBDDH;DBBLBDDH;BRAKBDDH",
      "routing|Routing Number|enum|055262965;055260123;055261847;055263310;055264092",
      "beneficiary|Beneficiary Setup|text|Smart Metal Accessories Ltd.;Smart Metal Export FZE;Smart Trims BD Ltd.",
      "bankRole|Bank Role|enum|Payment bank;LC bank;Both payment and LC;Collection only",
      CURRENCY,
      "baseCurrency|Base Currency|enum|USD;BDT;EUR",
      "exchangeRate|Exchange Rate|float|0.72;158;BDT;4",
      "convertedValue|Currency Conversion|money|4000;2400000",
      "forexPoints|Forex History Points|int|12;720",
      "bankCharges|Bank Charges|money|20;38000",
      "aiSuggestion|AI Currency Suggestion|text|Invoice this buyer in EUR to match their LC;Lock the contract rate at PI stage;Rate has moved 3% - requote before approval;Route through the USD account for lower charges;No change suggested",
      "approver|Approved By|person",
      "date|Rate Date|date|-330;0",
    ],
    statuses: ["Active", "Primary Account", "Pending Approval", "Under Verification", "Dormant", "Closed"],
    measure: "convertedValue", rows: 52,
    insight: "Multi-bank routing saves about USD 9k a year in charges, but only where the buyer's currency and the receiving account match — mismatched pairs give the spread straight back.",
    settings: [
      "Allow multiple banks and multiple currencies against a single buyer",
      "Refresh the exchange rate daily and keep the full forex history",
      "Require approval before a bank account is set as the primary receiving account",
    ],
  },

  /* ── 10 ─ Print, Preview & Export ──────────────────────────────────── */
  "print-preview-export": {
    name: "Print, Preview & Export", kind: "list", summary: "PDF, Excel, Word, email, QR and batch output",
    entity: "Print Job", ref: "PRN",
    fields: [
      PI_LINK, BUYER,
      "output|Output|enum|PI preview;Print PI;PDF export;Excel export;Word export;Email PI;Batch print;Batch export",
      "copyType|Copy|enum|Buyer copy;Internal copy;Bank copy;File copy",
      "template|Template Selection|enum|Standard export PI;Buyer branded PI;Compact PI;Detailed PI;LC submission PI;Custom template",
      "marks|Document Marks|enum|QR code;Barcode;Digital signature;Company logo;Watermark;QR code and barcode;All marks",
      "copies|Copies|int|1;12;copies",
      "pages|Pages|int|1;24;pages",
      "sizeMb|File Size|float|0.05;18;MB;2",
      "emailTo|Emailed To|text|merchandising@buyer.com;sourcing@zizzi.dk;docs@basicbank.com.bd;internal distribution;Not emailed",
      "historyType|History Entry|enum|Print history;Download history;Email history;Preview only",
      "requestedBy|Requested By|person",
      "date|Generated On|date|-300;0",
    ],
    statuses: ["Generated", "Printed", "Emailed", "Downloaded", "Queued", "Failed"],
    measure: "copies", rows: 58,
    insight: "The buyer copy and the bank copy print from the same record but different templates — the bank copy carries the full terms block and the digital signature panel, the buyer copy does not.",
    settings: [
      "Use the buyer's own print template when one is configured for them",
      "Stamp a QR code linking back to the live PI record on every printed copy",
      "Apply a DRAFT watermark to any PI printed before approval",
      "Attach the PDF automatically when a PI is emailed to the buyer",
    ],
  },

  /* ── 11 ─ PI Reports ───────────────────────────────────────────────── */
  "pi-reports": {
    name: "PI Reports", kind: "analytics", summary: "Buyer, style, marketing, country and currency reporting",
    entity: "PI Report", ref: "PRP",
    fields: [
      "reportType|Report|enum|Buyer wise PI report;Style wise PI report;Marketing wise PI report;Commercial wise PI report;Country wise PI report;Currency wise PI report;Pending PI report;Approved PI report;Cancel PI report;Amendment report;Revision report;PI value report;Shipment wise report;Date wise report;Monthly report;Yearly report;Summary report;Detail report",
      BUYER, STYLE, COUNTRY, CURRENCY, EXEC, COMMERCIAL, PERIOD,
      "records|Records|int|4;480;rows",
      "reportValue|Reported Value|money|8000;4800000",
      "depth|Report Depth|enum|Summary report;Detail report;Drill down",
      "format|Output|enum|On-screen;PDF export;Excel export;Scheduled email",
      "generatedBy|Generated By|person",
      "date|Generated On|date|-330;0",
    ],
    statuses: ["Published", "Generated", "Scheduled", "Draft", "Failed"],
    measure: "reportValue", rows: 60,
    insight: "Buyer-wise and currency-wise reports answer 70% of what the board actually asks for. The rest is nearly always a date-wise cut of the same rows.",
    settings: [
      "Default every report to the current financial year unless a period is chosen",
      "Let a summary report drill down into its detail rows in place",
      "Deliver scheduled reports as both PDF and Excel in one email",
    ],
  },

  /* ── 12 ─ Master Data Management ───────────────────────────────────── */
  "master-data-management": {
    name: "Master Data Management", kind: "list", summary: "Every master behind the PI, in one place",
    entity: "Master Record", ref: "MST",
    fields: [
      "masterType|Master|enum|Buyer master;Product master;Style master;Colour master;Size master;UOM master;Currency master;Bank master;Country master;Port master;Payment terms master;Shipment terms master;Incoterms master;Charge master;Document master;HS code master;Marketing person master;Commercial person master",
      "recordName|Record|text|Big Boss Corporation Ltd.;METAL ZIPPER #05 OPEN END;ST.J20143D;YKK-233;48.5 CM;Pcs;USD;Basic Bank Limited;Germany;Hamburg Port;Irrevocable LC at Sight;FOB;Freight;Packing Instruction;8308.10.00;Md. Rakib Hossain;Arifur Rahman",
      "recordCode|Record Code|code|MST",
      "records|Records in Master|int|4;1800",
      "duplicates|Duplicates|int|0;36",
      "completeness|Completeness|pct|42;100",
      "linkedPi|Linked PIs|int|0;180",
      "transfer|Data Import / Export|enum|Imported from Excel;Exported to Excel;Bulk updated;Manually entered;Synced from ERP",
      "owner|Data Owner|person",
      "date|Last Updated|date|-500;0",
    ],
    statuses: ["Active", "Under Review", "Draft", "Duplicate", "Archived"],
    measure: "records", rows: 60,
    insight: "Product and style masters carry every duplicate in the system. Both are fed by AI import, so the fix belongs at the mapping stage rather than in a periodic clean-up.",
    settings: [
      "Block a new master record when an existing one matches on name or code",
      "Require every master to be approved before it can be used on a PI",
      "Allow bulk import and export of any master as Excel",
    ],
  },

  /* ── 13 ─ Buyer Management ─────────────────────────────────────────── */
  "buyer-management": {
    name: "Buyer Management", kind: "list", summary: "Buyer profile, terms, credit, rating and history",
    entity: "Buyer", ref: "BYR",
    fields: [
      BUYER,
      "buyerCode|Buyer Code|code|BYR",
      "contactPerson|Contact Person|person",
      "address|Buyer Address|text|Aptech Industrial Park Holding No 30 Sarabo Kashimpur Gazipur;Master Samuelsgatan 46 Stockholm;Avenida Diputacion Arteixo;1155 Battery Street San Francisco;Weston Centre Dublin;Neuer Wall 12 Hamburg",
      COUNTRY, CURRENCY, PAYMENT_TERM,
      "buyerBank|Buyer Bank|enum|Deutsche Bank AG;HSBC London;BNP Paribas;Citibank NA;Bank of China;Nordea;Santander",
      "brand|Buyer Brand|enum|H&M;Zara;Levi's;Primark;Uniqlo;Decathlon;C&A;Bestseller;ZIZZI",
      "category|Buyer Category|enum|Key account;Strategic;Regular;New buyer;Dormant",
      "rating|Buyer Rating|pct|32;100",
      "creditLimit|Credit Limit|money|20000;4800000",
      "outstanding|Outstanding|money|0;2400000",
      "piHistory|PI History|int|1;180;PIs",
      "onTimePayment|Payment Performance|pct|38;100",
      "documents|Buyer Documents|int|0;24;files",
      "emailsSent|Email History|int|0;180;emails",
      "notes|Buyer Notes|text|Requires nickel-free declaration;Audits factory twice a year;Pays ahead of terms;Seasonal peak in Q3;Prefers consolidated shipments;Strict on lab dips",
      "date|Onboarded|date|-1200;-30",
    ],
    statuses: ["Active", "Pending Approval", "Under Review", "On Hold", "Dormant", "Archived", "Blacklisted"],
    measure: "creditLimit", rows: 50,
    insight: "Four key accounts hold 61% of the total credit limit. Two of them are running above 80% utilisation, which is where the next PI approval will start to stall.",
    settings: [
      "Require approval before a new buyer can have a PI raised against them",
      "Warn on PI entry when the buyer's outstanding passes 80% of their credit limit",
      "Archive a buyer automatically after 24 months with no PI activity",
    ],
  },

  /* ── 14 ─ Buying House Management ──────────────────────────────────── */
  "buying-house-management": {
    name: "Buying House Management", kind: "list", summary: "Agents, commission, mapping and agreements",
    entity: "Buying House", ref: "BHS",
    fields: [
      "house|Buying House|enum|Li & Fung Bangladesh;MGF Sourcing;Nassa Sourcing;Impactiva BD;Newtimes Global;Synergies Worldwide;Direct - no house",
      "houseCode|House Code|code|BHS",
      "contactPerson|Contact Person|person",
      "address|Address|text|Gulshan Avenue Dhaka;Banani Road 11 Dhaka;Agrabad Chattogram;Hong Kong Central;Ho Chi Minh District 1",
      COUNTRY,
      "buyerMapping|Buyer Mapping|enum|@buyers",
      "marketingMapping|Marketing Mapping|person",
      "brandMapping|Brand Mapping|enum|H&M;Zara;Levi's;Primark;Uniqlo;Decathlon;C&A;Bestseller",
      "commissionPct|Commission Rate|pct|0.5;12",
      "commissionValue|Commission Value|money|200;480000",
      "agreementRef|Agreement|enum|Annual agency agreement;Framework agreement;Commission only;Trial arrangement;Under renegotiation",
      "documents|Documents|int|0;24;files",
      "piHandled|PI History|int|1;140;PIs",
      "performance|Performance Score|pct|30;100",
      "emailsSent|Email History|int|0;140;emails",
      "activityEntries|Activity Log|int|1;96;entries",
      "date|Agreement From|date|-1100;-20",
    ],
    statuses: ["Active", "Under Agreement", "Pending Approval", "Suspended", "Expired", "Archived"],
    measure: "commissionValue", rows: 46,
    settings: [
      "Calculate commission from the approved PI value rather than the shipped value",
      "Require approval before a buying house is mapped to a new buyer",
      "Flag an agreement 60 days before it expires",
    ],
  },

  /* ── 15 ─ Product & Item Management ────────────────────────────────── */
  "product-item-management": {
    name: "Product & Item Management", kind: "list", summary: "Items, codes, HS, UOM, images and specification",
    entity: "Product", ref: "PRD",
    fields: [
      "itemCode|Item Code|code|ITM",
      ITEM,
      "description|Item Description|text|METAL ZIPPER #05 OPEN END TWO WAY WITH SPECIAL PULLER MZP-128;Antique brass ring snap with prong;Nickel-free tack button shank;Auto-lock slider with logo puller;Double-cap tubular rivet;Zinc alloy centre-bar buckle;Laser-etched metal label",
      "buyerItemCode|Buyer Item Code|enum|MZP-128;HM-24471;ZR-8802;LS-511X;PR-3390;UQ-7712;Not provided",
      "category|Product Category|enum|Snap fasteners;Jeans buttons;Zipper components;Rivets;Eyelets;Buckles;Metal labels",
      "productGroup|Product Group|enum|Metal trims;Plastic trims;Packaging;Hardware;Branding",
      "productType|Product Type|enum|Finished item;Component;Sub-assembly;Consumable;Sample only",
      "material|Material|enum|Brass;Zinc alloy;Stainless steel;Mild steel;Aluminium;Nickel-free brass;Copper alloy",
      HS_CODE, UOM,
      "image|Product Image|bool|Image uploaded;No image",
      "specification|Product Specification|text|Passes nickel release test EN 1811;Salt spray 24 hours no red rust;Tensile pull 90N minimum;Coating thickness 8 to 12 micron;Buyer manual rev 6;Standard specification",
      "itemMapping|Item Mapping|enum|Mapped to buyer code;Mapped to style;Mapped to BOM;Mapped to HS code;Unmapped",
      "barcode|Barcode / QR|enum|Barcode printed;QR code printed;Both printed;Not printed",
      "unitPrice|Unit Price|float|0.02;4.8;USD;4",
      "revisions|Product History Entries|int|1;36;entries",
      "date|Created On|date|-900;0",
    ],
    statuses: ["Active", "Sample Stage", "Under Development", "Discontinued", "Blocked"],
    measure: "unitPrice", rows: 58,
    settings: [
      "Generate the item code from the category and material automatically",
      "Require an HS code and a UOM before a product can go on a PI",
      "Print a barcode and QR code on every product specification sheet",
    ],
  },

  /* ── 16 ─ Style, Color & Size Management ───────────────────────────── */
  "style-color-size": {
    name: "Style, Color & Size Management", kind: "list", summary: "Styles, colours, sizes, ranges and mapping",
    entity: "Style Variant", ref: "STY",
    fields: [
      "sku|SKU|code|SKU",
      STYLE,
      "styleDescription|Style Description|text|Open end two way metal zipper with special puller;Denim five pocket trim set;Shirt button and thread pack;Jacket hardware set;Bag hardware assortment",
      BUYER_STYLE, BUYER,
      "season|Season|enum|SS26;AW26;SS27;AW27;Basic carry-over",
      "brand|Brand|enum|H&M;Zara;Levi's;Primark;Uniqlo;Decathlon;C&A;Bestseller;ZIZZI",
      COLOR,
      "colorGroup|Colour Group|enum|Metallics;Blacks and greys;Naturals;Brights;Enamels;Buyer standard",
      SIZE,
      "sizeGroup|Size Group|enum|Zipper lengths;Button lines;Snap diameters;Buckle widths;Eyelet bores",
      "sizeRange|Size Range|enum|45-52 CM;15-25mm;17L-24L;No. 3 to No. 8;4-9mm;Single size",
      "mapping|Mapping|enum|Style mapping;Colour mapping;Size mapping;Full mapping applied;Not mapped",
      "styleImage|Style Image|bool|Image uploaded;No image",
      "specification|Specification|text|Tape DTM colour teeth and slider;Puller plus top and bottom stopper shiny silver;Right insert left hand puller;Bottom stopper box type;Y type teeth;Standard specification",
      "variants|Product Variants|int|1;48",
      "date|Created On|date|-700;0",
    ],
    statuses: ["Active", "Approved", "Pending Approval", "Superseded", "Discontinued"],
    measure: "variants", rows: 66,
    insight: "One buyer style routinely fans out into eight or more SKUs once colour and size are applied — the variant count is what actually drives the tooling and packing plan.",
    settings: [
      "Generate the SKU automatically from style, colour and size",
      "Require buyer approval on a colour before it can be used on a PI",
      "Keep superseded style versions visible in history rather than deleting them",
    ],
  },

  /* ── 17 ─ Quantity & Unit Management ───────────────────────────────── */
  "quantity-unit-management": {
    name: "Quantity & Unit Management", kind: "list", summary: "Order, pack, carton, balance and conversion",
    entity: "Quantity Line", ref: "QTY",
    fields: [
      PI_LINK, ITEM, UOM,
      "conversion|Unit Conversion|enum|1 Gross = 144 Pcs;1 Dozen = 12 Pcs;1 Set = 2 Pcs;1 Carton = 10 Gross;1 Kg = 1200 Pcs;No conversion",
      "packingRatio|Packing Ratio|enum|1:1;2:2:2;S1-M2-L2-XL1;12 per polybag;144 per box;500 per bag",
      "moq|MOQ|int|500;144000;Pcs",
      "orderQty|Order Quantity|int|50;2400000;Pcs",
      "productionQty|Production Quantity|int|0;2400000;Pcs",
      "shipmentQty|Shipment Quantity|int|0;2400000;Pcs",
      "balanceQty|Balance Quantity|int|0;980000;Pcs",
      "cartonQty|Carton Quantity|int|1;2400;cartons",
      "adjustment|Quantity Adjustment|int|0;24000;Pcs",
      "tolerancePct|Tolerance|pct|0;10",
      "validation|Quantity Validation|text|Within agreed tolerance;Below the item MOQ;Over tolerance - amendment needed;Conversion applied at PI line;Shipment exceeds balance;Validates clean",
      "historyEntries|Quantity History|int|1;36;entries",
      "approver|Adjustment Approved By|person",
      "date|Booked On|date|-300;0",
    ],
    statuses: ["Within Tolerance", "Balance Open", "Fully Shipped", "Below MOQ", "Over Tolerance", "Adjusted"],
    measure: "orderQty", rows: 60,
    insight: "Where the buyer orders in gross and we plan in pieces, the conversion is applied once at the PI line — the balance quantity is always in pieces so shipments reconcile cleanly.",
    settings: [
      "Warn when an order quantity falls below the item MOQ",
      "Accept shipment quantities inside the agreed tolerance without an amendment",
      "Require approval for any manual quantity adjustment above 1% of the order",
    ],
  },

  /* ── 18 ─ Price & Costing Management ───────────────────────────────── */
  "price-costing": {
    name: "Price & Costing Management", kind: "analytics", summary: "FOB, CIF, cost sheet, margin and AI price",
    entity: "Price Line", ref: "PRC",
    fields: [
      ITEM, BUYER, CURRENCY,
      "buyerPrice|Buyer Price|float|0.02;4.8;USD;4",
      "fobPrice|FOB Price|float|0.02;4.8;USD;4",
      "cifPrice|CIF Price|float|0.02;5.4;USD;4",
      "costSheetRef|Cost Sheet|enum|CS-26-1104;CS-26-1127;CS-26-1148;CS-26-1163;CS-26-1189;Not costed",
      "materialCost|Material Cost|money|100;980000",
      "accessoriesCost|Accessories Cost|money|20;280000",
      "cmCost|CM Cost|money|50;480000",
      "freightCost|Freight Cost|money|0;180000",
      "insuranceCost|Insurance Cost|money|0;48000",
      "otherCost|Other Cost|money|0;98000",
      "totalCost|Total Cost|money|200;1800000",
      "totalAmount|Total Amount|money|4000;2400000",
      "marginPct|Profit Margin|pct|2;46",
      "comparison|Cost Comparison|text|4% above the last approved price;In line with the buyer contract rate;Below the target margin floor;Brass cost has moved since costing;Cheaper than the previous season;No comparable history",
      "aiSuggestedPrice|AI Price Suggestion|float|0.02;5.1;USD;4",
      "approver|Price Approval|person",
      "revisions|Price History Entries|int|1;24;entries",
      "date|Priced On|date|-330;0",
    ],
    statuses: ["Approved", "Above Target Margin", "On Target", "Below Target", "Loss Making", "Under Review"],
    measure: "totalAmount", rows: 62,
    insight: "The AI suggestion sits 4–7% above the quoted price on repeat items where metal cost has moved since the last agreement — that gap is the single largest recoverable margin in the book.",
    settings: [
      "Require approval on any price that falls below the target margin",
      "Recalculate FOB and CIF automatically from the cost sheet and charges",
      "Show the AI price suggestion alongside the quoted price during PI entry",
    ],
  },

  /* ── 19 ─ Charges Management ───────────────────────────────────────── */
  "charges-management": {
    name: "Charges Management", kind: "list", summary: "Freight, insurance, packing, bank and commission",
    entity: "Charge Sheet", ref: "CHG",
    fields: [
      PI_LINK, BUYER,
      "chargeSetup|Charge Setup|enum|Per PI;Per line;Percentage of value;Fixed amount;Per carton;Per container",
      "freight|Freight Charge|money|0;180000",
      "insurance|Insurance Charge|money|0;48000",
      "packing|Packing Charge|money|0;98000",
      "documentation|Documentation Charge|money|0;24000",
      "sampleCharge|Sample Charge|money|0;24000",
      "testing|Testing Charge|money|0;38000",
      "bankCharge|Bank Charge|money|0;38000",
      "commission|Commission Charge|money|0;280000",
      "discount|Discount|money|0;180000",
      "otherCharges|Other Charges|money|0;68000",
      "calculated|Charge Calculation|money|50;2800000",
      "aiValidation|AI Charge Validation|text|Freight looks high for this lane;Insurance below the LC required 110%;Bank charge duplicated from the last PI;Commission rate differs from the agreement;Charges validate clean",
      "approver|Approved By|person",
      "historyEntries|Charge History|int|1;24;entries",
      "date|Costed On|date|-330;0",
    ],
    statuses: ["Finalised", "Approved", "Provisional", "Under Review", "Disputed", "Cancelled"],
    measure: "calculated", rows: 58,
    insight: "Charges add a median 6.8% on top of goods value. Air freight recovery and third-party inspection are the two heads that move it past 12% on rush orders.",
    settings: [
      "Apply the buyer's default charge setup automatically on a new PI",
      "Require approval when total charges exceed 10% of the goods value",
      "Import and export the charge sheet as Excel for the finance team",
    ],
  },

  /* ── 20 ─ Payment Terms Management ─────────────────────────────────── */
  "payment-terms": {
    name: "Payment Terms Management", kind: "list", summary: "LC, TT, CAD, DA/DP, credit days and schedule",
    entity: "Payment Term", ref: "PAY",
    fields: [
      PI_LINK, BUYER,
      "termOwner|Applies To|enum|Buyer payment terms;Supplier payment terms;Both",
      "paymentMode|Payment Mode|enum|LC at Sight;Usance LC;TT payment;Advance payment;CAD;DA;DP",
      PAYMENT_TERM,
      "advancePct|Advance Payment|pct|0;100",
      "creditDays|Credit Days|int|0;180;days",
      "amount|Amount|money|4000;2400000",
      "received|Received|money|0;2400000",
      "scheduleStage|Payment Schedule|enum|On PI acceptance;On LC receipt;On shipment;On document acceptance;30 days after BL;On delivery",
      "reminderSent|Reminder|bool|Reminder sent;No reminder",
      "approver|Approved By|person",
      "dueDate|Due Date|date|-90;150",
      "date|Agreed On|date|-330;0",
    ],
    statuses: ["Received", "Partially Received", "Scheduled", "Pending Approval", "Overdue", "Written Off"],
    measure: "amount", rows: 58,
    insight: "LC-backed PIs settle 11 days later than TT on average but carry a fifth of the overdue value — the credit-days column, not the term type, is what predicts a late payment.",
    settings: [
      "Calculate the due date from the credit days and the shipment date",
      "Send a payment reminder seven days before the due date and again on it",
      "Require approval before a buyer's standard payment terms are overridden on a PI",
    ],
  },

  /* ── 21 ─ Marketing Executive Management ───────────────────────────── */
  "marketing-executive": {
    name: "Marketing Executive Management", kind: "analytics", summary: "Assignment, target, visits, incentive and KPI",
    entity: "Executive Record", ref: "MKT",
    fields: [
      EXEC,
      "employeeCode|Employee Mapping|code|EMP",
      "buyerAssigned|Buyer Assignment|enum|@buyers",
      "houseAssigned|Buying House Assignment|enum|Li & Fung Bangladesh;MGF Sourcing;Nassa Sourcing;Impactiva BD;Newtimes Global;Direct - no house",
      "territory|Territory|enum|Europe;North America;Far East;Middle East;Australia;Local market",
      "visitPlan|Customer Visit Plan|int|0;24;visits",
      "followUps|Follow-ups|int|0;68",
      "inquiriesAssigned|Inquiry Assignment|int|0;48;files",
      "piAssigned|PI Assignment|int|1;96;PIs",
      "target|Sales Target|money|40000;2400000",
      "achieved|Achieved|money|0;2400000",
      "achievement|Target Achievement|pct|18;145",
      "incentive|Incentive|money|0;68000",
      "commission|Commission|money|200;180000",
      "activityEntries|Activity Log|int|1;180;entries",
      "calendarEvents|Calendar Events|int|0;48;events",
      "reminders|Reminders|int|0;36",
      "approver|Approved By|person",
      "date|Period End|date|-330;0",
    ],
    statuses: ["Above Target", "On Target", "Below Target", "Pending Approval", "Under Review"],
    measure: "achieved", rows: 50,
    insight: "Visit frequency tracks almost linearly with target achievement up to about twelve visits a period, then flattens — beyond that the constraint is capacity, not coverage.",
    settings: [
      "Assign a new inquiry or PI automatically to the executive who owns that buyer",
      "Calculate incentive on collected value rather than on raised PI value",
      "Remind an executive when a planned customer visit has not been logged",
    ],
  },

  /* ── 22 ─ AI Buyer PO Mapping ──────────────────────────────────────── */
  "ai-po-mapping": {
    name: "AI Buyer PO Mapping", kind: "list", summary: "Buyer PO columns mapped to PI fields",
    entity: "Mapping Profile", ref: "MAP",
    fields: [
      BUYER,
      "poFile|Buyer PO Upload|text|BuyerPO-4471.pdf;OrderSheet-Q2.xlsx;PO58125.pdf;Scanned-PO-882.jpg;Bulk-Upload.zip",
      "template|Buyer Template|enum|H&M order sheet v4;Zara PO layout;Levi bulk template;Primark trim sheet;Uniqlo order form;Decathlon PO;Auto-detected layout",
      "sourceColumn|Buyer Column|text|Article No;Colour Way;Size Break;Unit Of Measure;Currency Code;Vendor Name;Ship Date;Unit Rate",
      "targetField|Maps To|enum|Auto buyer detection;Auto style mapping;Auto product mapping;Auto colour mapping;Auto size mapping;Auto quantity mapping;Auto price mapping;Auto currency mapping",
      "matchMethod|Match Method|enum|Exact match;Dictionary match;Fuzzy match;AI smart matching;Manual override",
      "matchScore|Match Confidence|pct|48;100",
      "mappedFields|Fields Mapped|int|4;64",
      "missingData|Missing Data Detected|int|0;18;fields",
      "duplicatePo|Duplicate PO Detection|bool|Duplicate found;No duplicate",
      "comparison|PO vs PI Comparison|text|Quantity differs by 4% on two lines;Price matches the PO exactly;Currency differs - PO in EUR PI in USD;Delivery date earlier on the PO;Sizes not present on the PI;Fully reconciled",
      "aiSuggestion|AI Suggestion|text|Save this layout as a buyer profile;Split the size break cell before mapping;Map Vendor Name to seller not buyer;Confirm the currency before creating the PI;Accept the mapping as scored",
      "errors|Errors Detected|int|0;12",
      "autoPi|Auto PI Creation|bool|PI auto-created;Held for review",
      "profileSaved|Mapping Profile|bool|Saved profile;One-off mapping",
      "approver|Approved By|person",
      "date|Last Mapped|date|-300;0",
    ],
    statuses: ["Mapped", "PI Created", "AI Suggested", "Needs Review", "Manual Override", "Unmapped"],
    measure: "mappedFields", rows: 58,
    insight: "Saved buyer profiles resolve 89% of columns without a prompt. Size breaks are the weak point — buyers who ship an S/M/L grid in one cell still need a manual override.",
    settings: [
      "Reuse the saved mapping profile whenever the buyer template is detected",
      "Ask for confirmation when AI smart matching scores below 80%",
      "Compare every mapped PO against the resulting PI before it is created",
    ],
  },

  /* ── 23 ─ AI Data Validation ───────────────────────────────────────── */
  "ai-data-validation": {
    name: "AI Data Validation", kind: "list", summary: "Every field checked before a PI is submitted",
    entity: "Validation Finding", ref: "VAL",
    fields: [
      PI_LINK, BUYER,
      "checkType|Check|enum|Buyer validation;Style validation;Product validation;Colour validation;Size validation;Quantity validation;Price validation;Currency validation;Payment terms validation;Bank validation;LC validation;Duplicate validation;Mandatory field check",
      "severity|Severity|enum|Critical;High;Medium;Low;Information",
      "findings|Findings|int|0;24",
      "mandatoryMissing|Mandatory Fields Missing|int|0;12;fields",
      "autoCorrected|Auto Corrected|int|0;18",
      "aiSuggestion|AI Suggestion|text|Copy price from last approved PI;Merge with duplicate PI-2026-000131;Convert gross to pieces;Apply HS 8308.10.00;Use buyer contract rate;Add missing delivery date;Correct the SWIFT code",
      "confidence|AI Confidence|pct|45;99.5",
      "valueAtRisk|Value at Risk|money|0;680000",
      "approver|Approved By|person",
      "historyEntries|Validation History|int|1;24;entries",
      "verifiedBy|Verified By|person",
      "date|Checked On|date|-300;0",
    ],
    statuses: ["Verified", "Auto Corrected", "AI Suggested", "Open", "Ignored"],
    measure: "valueAtRisk", rows: 62,
    insight: "Duplicate detection catches roughly one PI in forty — almost all of them a re-import of the same buyer PO under a new file name rather than a genuine second order.",
    settings: [
      "Block submission while any critical validation finding is open",
      "Apply auto-correction only when AI confidence exceeds 90%",
      "Run the full validation set automatically every time a PI is saved",
    ],
  },

  /* ── 24 ─ Shipment & Delivery Information ──────────────────────────── */
  "shipment-delivery": {
    name: "Shipment & Delivery Information", kind: "list", summary: "Ports, ETD, ETA, vessel, container and tracking",
    entity: "Shipment Plan", ref: "SHP",
    fields: [
      PI_LINK, BUYER,
      "shipmentPlan|Shipment Plan|enum|Full shipment;Partial shipment - part 1;Partial shipment - part 2;Consolidated shipment;Sample shipment",
      "vessel|Vessel Information|enum|MAERSK CHENNAI V.242W;MSC LORETO V.318E;CMA CGM BENJAMIN FRANKLIN;HAPAG EXPRESS ROME;ONE APUS V.077;Air - EK585;Not assigned",
      "container|Container Information|enum|MSKU4471882 20ft GP;TGHU8802331 40ft GP;CMAU5150447 40ft HC;LCL consolidation;Air ULD;Not assigned",
      POL, POD,
      "deliveryTerms|Delivery Terms|enum|FOB Chattogram;CIF Hamburg;CFR Rotterdam;EXW Gazipur;DDP Barcelona;FCA Dhaka ICD",
      "mode|Shipment Mode|enum|Sea Freight FCL;Sea Freight LCL;Air freight;Courier;Road;Multimodal",
      "carrier|Carrier|enum|Maersk;MSC;CMA CGM;Hapag-Lloyd;ONE;Emirates SkyCargo;DHL Express",
      "trackingRef|Tracking Reference|enum|MAEU4471882201;MSCU7788345612;CMAU990112447;DHL 4471882201;Not tracked",
      "shipmentValue|Shipment Value|money|4000;2400000",
      "documents|Shipment Documents|int|0;12;files",
      "alert|Shipment Alert|bool|Alert raised;No alert",
      "approver|Approved By|person",
      "etd|ETD|date|-60;150",
      "eta|ETA|date|-40;180",
      "deliveryDate|Delivery Schedule|date|-30;200",
      "date|Booked On|date|-300;0",
    ],
    statuses: ["Delivered", "In Transit", "Loaded", "Booked", "Planned", "Delayed"],
    measure: "shipmentValue", rows: 60,
    insight: "ETA slips more often than ETD does — the sailing leaves on time and loses the days at transhipment, which is why the delivery schedule is tracked separately from the ETA.",
    settings: [
      "Alert the buyer automatically seven days before every ETD",
      "Allow partial shipments only where the LC and the PI both permit them",
      "Require approval before an ETD is moved after the buyer has been notified",
    ],
  },

  /* ── 25 ─ Container & Packing Management ───────────────────────────── */
  "container-packing": {
    name: "Container & Packing Management", kind: "list", summary: "Cartons, weight, CBM, booking and seals",
    entity: "Packing Plan", ref: "PKG",
    fields: [
      PI_LINK, BUYER,
      "packingList|Packing List|code|PL",
      "cartonDetails|Carton Details|text|Export carton 5 ply brown;Master carton with inner polybags;Buyer branded carton;Pallet on shrink wrap;Drum packing",
      "cartonMeasure|Carton Measurement|enum|60x40x40 cm;50x35x30 cm;45x30x25 cm;80x60x50 cm;Pallet 120x100x150 cm",
      "cartons|Carton Quantity|int|1;2400;cartons",
      "netWeight|Net Weight|float|20;24000;kg;1",
      "grossWeight|Gross Weight|float|22;26000;kg;1",
      "cbm|CBM|float|0.4;68;CBM;2",
      "containerBooking|Container Booking|enum|Booked with carrier;Booking requested;Space confirmed;LCL consolidation;Not booked",
      "containerNo|Container Number|enum|MSKU4471882;TGHU8802331;CMAU5150447;HLXU6280194;Not assigned",
      "sealNo|Seal Number|enum|BD0447188;BD0880233;BD0515044;BD0628019;Not sealed",
      "containerType|Container Type|enum|20ft GP;40ft GP;40ft HC;LCL consolidation;Air ULD",
      "packingInstruction|Packing Instruction|text|144 per box then 10 boxes per carton;500 per polybag with desiccant;Buyer manual rev 6;Shrink wrap each carton;Individual blister packing",
      "utilisation|Container Utilisation|pct|28;100",
      "marks|Barcode / QR|enum|Barcode on carton;QR code on carton;Both printed;Buyer label only;Not printed",
      "approver|Approved By|person",
      "loadingDate|Loading Date|date|-60;120",
      "date|Planned On|date|-300;0",
    ],
    statuses: ["Shipped", "Sealed", "Loaded", "Cartons Ready", "Planned", "Pending Approval"],
    measure: "cbm", rows: 58,
    insight: "Average container utilisation is 78%. Metal trims are dense enough that weight, not volume, is the binding limit on roughly a third of bookings.",
    settings: [
      "Calculate CBM and gross weight automatically from carton measurement and count",
      "Print a barcode and QR code on every carton label",
      "Warn when container utilisation falls below 70% on an FCL booking",
    ],
  },

  /* ── 26 ─ Document & Attachment Management ─────────────────────────── */
  "document-attachment": {
    name: "Document & Attachment Management", kind: "list", summary: "PO, LC, PI, artwork, reports and versions",
    entity: "Attachment", ref: "DOC",
    fields: [
      PI_LINK, BUYER,
      "docType|Document Type|enum|Buyer PO upload;LC upload;PI attachment;Invoice attachment;Packing list attachment;Test report upload;Artwork upload;Technical sheet upload;Specification upload;Image upload;PDF upload",
      "fileName|File Name|text|BuyerPO-4471.pdf;LC-2026-4471.pdf;PI-2026-000125.pdf;Artwork-MZP128.ai;TestReport-SGS.pdf;TechSheet-rev6.xlsx;CartonLabel.png",
      "format|Format|enum|PDF;Excel;Word;Image;AI / vector;ZIP archive",
      "sizeMb|File Size|float|0.05;48;MB;2",
      "version|Version Control|int|1;8",
      "downloads|Downloads|int|0;96",
      "previewAvailable|Preview|bool|Preview available;Download only",
      "approver|Approved By|person",
      "uploadedBy|Uploaded By|person",
      "archived|Archive|bool|Archived;Live",
      "date|Uploaded On|date|-330;0",
    ],
    statuses: ["Verified", "Uploaded", "Pending Approval", "Superseded", "Archived", "Rejected"],
    measure: "sizeMb", rows: 66,
    settings: [
      "Keep every prior version of a document rather than overwriting it",
      "Require approval before a buyer-facing document is marked verified",
      "Archive attachments automatically once their PI is closed",
    ],
  },

  /* ── 27 ─ Export Documentation Center ──────────────────────────────── */
  "export-documentation": {
    name: "Export Documentation Center", kind: "list", summary: "Invoice, packing list, CO, GSP, EXP and BL",
    entity: "Export Document", ref: "EXD",
    fields: [
      PI_LINK, BUYER,
      "docType|Document|enum|Commercial invoice;Packing list;Certificate of origin;GSP certificate;EXP form;Bill of lading;Air way bill;Fumigation certificate;Inspection certificate;Shipping bill",
      "docNumber|Document Number|code|EXD",
      "issuingBody|Issued By|enum|Own issue;Chamber of Commerce;Export Promotion Bureau;Customs;SGS;Bureau Veritas;Intertek;Shipping line",
      "autoGenerated|Auto Generation|bool|Auto generated from PI;Manually prepared",
      "checklistDone|Document Checklist|pct|20;100",
      "copies|Copies|int|1;8;copies",
      "trackingRef|Tracking Reference|enum|DHL 4471882201;FedEx 7788345612;Courier BD 990112;Bank courier;Hand delivered",
      "approver|Approved By|person",
      "archived|Archive|bool|Archived;Live",
      "issueDate|Issue Date|date|-300;30",
      "date|Prepared On|date|-330;0",
    ],
    statuses: ["Issued", "Submitted to Bank", "In Preparation", "Pending Approval", "Archived", "Rejected"],
    measure: "checklistDone", rows: 60,
    insight: "Documents rejected by the negotiating bank are almost always the certificate of origin — a mismatch between the HS code on the invoice and the one on the certificate.",
    settings: [
      "Generate the commercial invoice and packing list straight from the approved PI",
      "Hold the document set until every checklist item is ticked",
      "Archive the full document set automatically once payment is received",
    ],
  },

  /* ── 28 ─ Buyer Contract Management ────────────────────────────────── */
  "buyer-contract": {
    name: "Buyer Contract Management", kind: "list", summary: "Agreements, clauses, renewal and expiry",
    entity: "Contract", ref: "CNT",
    fields: [
      BUYER,
      "contractNo|Contract Number|code|CNT",
      "contractType|Contract Type|enum|Annual supply agreement;Framework agreement;Price agreement;Exclusivity agreement;Trial contract",
      "contractTerms|Contract Terms|text|Fixed price for twelve months;Volume rebate above 5M pcs;Exclusive supply for denim trims;90 day payment terms;Annual price review in January",
      "paymentClause|Payment Clause|enum|Irrevocable LC at Sight;LC 90 days;TT 30 days;30% advance + 70% LC;CAD",
      "deliveryClause|Delivery Clause|text|Delivery within 45 days of LC receipt;Partial shipment allowed;Transhipment not permitted;FOB Chattogram;Buyer nominated forwarder",
      "qualityClause|Quality Clause|text|Nickel release per EN 1811;AQL 2.5 major 4.0 minor;Third party inspection before shipment;Buyer manual rev 6;Salt spray 24 hours",
      "penaltyClause|Penalty Clause|pct|0;10",
      "contractValue|Contract Value|money|40000;4800000",
      "utilised|Utilised|money|0;4800000",
      "amendments|Amendments|int|0;6",
      "renewalTerm|Renewal|enum|Auto renew annually;Renew on review;One-off contract;Under renegotiation;Not renewing",
      "documents|Document Upload|int|0;12;files",
      "reminderSent|Reminder|bool|Renewal reminder sent;No reminder",
      "approver|Approved By|person",
      "startDate|Validity From|date|-900;0",
      "expiryDate|Validity To|date|-60;500",
    ],
    statuses: ["Active", "Under Negotiation", "Pending Approval", "Renewal Due", "Expired", "Terminated", "Archived"],
    measure: "contractValue", rows: 48,
    insight: "Six contracts covering USD 2.1M expire inside the next quarter. Renewal discussions normally take eleven weeks, so three of them are already late to start.",
    settings: [
      "Raise a renewal reminder 90 days before a contract expires",
      "Apply the contract price automatically when a PI is raised for that buyer",
      "Require legal sign-off before a penalty or quality clause is amended",
    ],
  },

  /* ── 29 ─ PI Amendment Management ──────────────────────────────────── */
  "pi-amendment": {
    name: "PI Amendment Management", kind: "list", summary: "Amendment requests, approval and version tracking",
    entity: "Amendment", ref: "AMD",
    fields: [
      PI_LINK, BUYER,
      "amendmentNo|Amendment No|enum|A1;A2;A3;A4;A5",
      "amendmentType|Amendment Type|enum|Price amendment;Quantity amendment;Shipment amendment;Payment amendment;Buyer amendment;Style amendment;Document amendment",
      "beforeValue|Before|money|4000;2400000",
      "afterValue|After|money|4000;2800000",
      "variance|Variance|pct|0;68",
      "versionTracked|Version Tracking|enum|V1.0 to V1.1;V1.1 to V1.2;V1.2 to V2.0;V2.0 to V2.1;V2.1 to V3.0",
      "remarks|Remarks|text|Buyer increased the size break;Metal cost passed through;Vessel rolled to next sailing;Agreed at the Dhaka meeting;Correcting a data entry error",
      "notified|Notification|bool|Buyer notified;Not notified",
      "requestedBy|Requested By|person",
      "approver|Amendment Approval|person",
      "historyEntries|Amendment History|int|1;12;entries",
      "archived|Archive|bool|Archived;Live",
      "date|Raised On|date|-330;0",
    ],
    statuses: ["Approved", "Under Review", "Requested", "Rejected", "Cancelled", "Archived"],
    measure: "afterValue", rows: 56,
    insight: "Amendments raised after LC issuance cost an average USD 180 in bank amendment charges — worth catching at the revision stage before the LC goes out.",
    settings: [
      "Notify the buyer automatically when an amendment is approved",
      "Require a fresh approval cycle whenever the PI value moves by more than 5%",
      "Keep the pre-amendment version available for comparison and print",
    ],
  },

  /* ── 30 ─ PI Revision Management ───────────────────────────────────── */
  "pi-revision": {
    name: "PI Revision Management", kind: "list", summary: "Revision numbers, comparison, restore and change log",
    entity: "Revision", ref: "REV",
    fields: [
      PI_LINK, BUYER,
      "revisionNo|Revision Number|enum|R1;R2;R3;R4;R5;R6",
      "changedField|Changed Field|enum|Order quantity;Unit price;Delivery date;Payment terms;Currency;Buyer address;Item description;Shipping mode",
      "oldValue|Previous Value|text|180000 Pcs;USD 0.5800;15 Mar 2026;Irrevocable LC at Sight;USD;FOB Chattogram;Antique brass finish",
      "newValue|Revised Value|text|216000 Pcs;USD 0.6100;29 Mar 2026;LC 30 days;EUR;CIF Hamburg;Gunmetal finish",
      "reason|Reason of Revision|enum|Buyer request;Price renegotiated;Vessel rolled;Data entry error;Compliance requirement;Internal correction",
      "valueImpact|Value Impact|money|0;680000",
      "changeLogEntries|Change Log|int|1;42;entries",
      "versionRef|Version Control|enum|V1.0;V1.1;V1.2;V2.0;V2.1;V3.0",
      "documentUpdated|Document Update|bool|Documents reissued;Documents unchanged",
      "restored|Restore Version|bool|Restored from earlier version;Not restored",
      "notified|Notification|bool|Buyer notified;Not notified",
      "requestedBy|Requested By|person",
      "approver|Revision Approval|person",
      "remarks|Remarks|text|Buyer increased the size break;Metal cost passed through;Vessel rolled to next sailing;Agreed at the Dhaka meeting;Correcting a data entry error",
      "date|Requested On|date|-300;0",
    ],
    statuses: ["Approved", "Under Review", "Requested", "Restored", "Rejected", "Archived"],
    measure: "valueImpact", rows: 56,
    insight: "Quantity and delivery date account for four revisions in five. Price revisions are rare but carry 63% of the total value impact.",
    settings: [
      "Increment the revision number automatically on every approved change",
      "Reissue the printed PI whenever a revision is approved",
      "Keep every revision restorable rather than archiving it away",
    ],
  },

  /* ── 31 ─ PI Version Control ───────────────────────────────────────── */
  "pi-version-control": {
    name: "PI Version Control", kind: "list", summary: "Versions, snapshots, locking, release and archive",
    entity: "Version", ref: "VER",
    fields: [
      PI_LINK,
      "versionNo|Version Number|enum|V1.0;V1.1;V1.2;V2.0;V2.1;V3.0",
      "autoNumbered|Auto Version Number|bool|Auto numbered;Manually numbered",
      "changes|Change Tracking Entries|int|1;42;changes",
      "revisionNotes|Revision Notes|text|Quantity increased on two size lines;Price updated to the new contract rate;Delivery date pushed one sailing;Bank details corrected;Buyer address updated;Initial version",
      "changedBy|User Activity|person",
      "snapshotKb|Snapshot Size|float|12;980;KB;1",
      "locked|Lock Version|bool|Locked;Unlocked",
      "released|Release Version|bool|Released to buyer;Internal only",
      "comparison|Compare Changes|text|3 fields differ from V1.0;7 fields differ from V1.1;Value differs by USD 12400;Identical to the prior version;First version - nothing to compare",
      "downloads|Downloads|int|0;48",
      "prints|Prints|int|0;24;copies",
      "approver|Approval History|person",
      "archived|Archive Version|bool|Archived;Live",
      "date|Version Date|date|-330;0",
    ],
    statuses: ["Current Version", "Released", "Pending Approval", "Locked", "Superseded", "Archived"],
    measure: "changes", rows: 58,
    insight: "Every save writes a snapshot, so any prior version can be compared field by field and restored — the locked versions are the ones already sent to a buyer or a bank.",
    settings: [
      "Lock a version automatically once the PI reaches approved status",
      "Keep a full snapshot of every version rather than a change delta",
      "Notify the version owner whenever a locked version is downloaded",
    ],
  },

  /* ── 32 ─ Notification & Reminder Center ───────────────────────────── */
  "notification-reminder": {
    name: "Notification & Reminder Center", kind: "list", summary: "Email, SMS, push, in-app alerts and escalation",
    entity: "Notification", ref: "NTF",
    fields: [
      "channel|Channel|enum|Email notification;SMS notification;In-app notification;Push notification;Dashboard alert;Custom notification",
      "reminderType|Reminder|enum|Approval reminder;PI expiry reminder;LC expiry reminder;Shipment reminder;Payment reminder;Task reminder;Due date alert;Escalation alert",
      "audience|Audience|enum|Buyer notification;Marketing notification;Commercial team;Finance team;Management;Specific user",
      "recipient|Recipient|person",
      BUYER, PI_LINK,
      "message|Message|text|PI awaiting your approval for three days;LC expires in 14 days;Payment due tomorrow;Shipment ETD confirmed;Task overdue - please action;Buyer has replied on the PI",
      "scheduled|Schedule|enum|Immediate;Daily digest;Before due date;On escalation;Custom schedule",
      "leadHours|Sent Before Due|int|1;168;hrs",
      "retries|Retries|int|0;5",
      "escalatedTo|Escalated To|person",
      "dueDate|Due Date|date|-45;90",
      "date|Triggered On|date|-300;0",
    ],
    statuses: ["Read", "Delivered", "Sent", "Scheduled", "Snoozed", "Escalated", "Failed"],
    measure: "retries", rows: 66,
    settings: [
      "Send an approval reminder every 24 hours while a PI sits unactioned",
      "Escalate to SMS when an email notification is unread for two days",
      "Let each user choose which reminders reach them and on which channel",
    ],
  },

  /* ── 33 ─ Commercial Calendar ──────────────────────────────────────── */
  "commercial-calendar": {
    name: "Commercial Calendar", kind: "calendar", summary: "Shipments, LC expiry, payments, visits and tasks",
    entity: "Calendar Event", ref: "CAL",
    fields: [
      "eventType|Event|enum|PI schedule;Shipment schedule;LC expiry;Payment due;Delivery schedule;Holiday;Buyer visit;Marketing activity;Task;Reminder",
      BUYER, PI_LINK,
      "owner|Owner|person",
      "view|Calendar View|enum|Monthly view;Weekly view;Daily view;Timeline view",
      "value|Value at Stake|money|0;2400000",
      "leadDays|Lead Time|int|0;90;days",
      "syncSource|Calendar Sync|enum|Outlook sync;Google Calendar sync;Internal only;Mobile app;Not synced",
      "notified|Notification|bool|Reminder sent;No reminder",
      "eventDate|Event Date|date|-60;150",
      "date|Scheduled On|date|-300;0",
    ],
    statuses: ["Scheduled", "Due Soon", "Completed", "Overdue", "Cancelled"],
    measure: "value", rows: 68,
    insight: "Three LC expiries fall inside the Eid holiday week when the banks are shut. Those documents have to be presented the week before or they miss their window.",
    settings: [
      "Block the national holiday calendar out of every shipment and payment schedule",
      "Sync commercial events to each user's Outlook or Google calendar",
      "Show the timeline view by default on the mobile layout",
    ],
  },

  /* ── 34 ─ Approval Workflow ────────────────────────────────────────── */
  "approval-workflow": {
    name: "Approval Workflow", kind: "board", summary: "Draft, submit, review, approve, reject and return",
    entity: "Approval", ref: "APR",
    fields: [
      PI_LINK, BUYER,
      "value|PI Value|money|4000;2400000",
      "level|Approval Level|enum|Level 1 - Merchandiser;Level 2 - Marketing Manager;Level 3 - Commercial Head;Level 4 - Finance;Level 5 - Managing Director",
      "role|User Role|enum|Merchandiser;Marketing Manager;Commercial Head;Finance Officer;Managing Director;Administrator",
      "action|Action|enum|Submitted for approval;Approved;Rejected;Returned for correction;Escalated;On hold",
      "comments|Approval Comments|text|Approved as submitted;Check the freight recovery before approval;Buyer credit limit is nearly full;Price below target margin - justify;Returned - delivery date missing;Escalated past SLA",
      "approvalMode|Approval Mode|enum|Desktop approval;Mobile approval;Digital signature;Email approval",
      "submittedBy|Submitted By|person",
      "approver|Approver|person",
      "pendingDays|Pending For|int|0;30;days",
      "escalated|Escalation|bool|Escalated;Not escalated",
      "historyEntries|Approval History|int|1;12;entries",
      "date|Submitted On|date|-300;0",
    ],
    statuses: ["Draft", "Submitted", "Under Review", "Approved", "Returned", "On Hold", "Rejected"],
    measure: "value", rows: 62,
    insight: "The commercial head stage holds the queue: 71% of total pending days sit there, and nearly all of it is on PIs above the dual-approval threshold.",
    settings: [
      "Route a PI through multi-level approval once it passes the value threshold",
      "Email every approver the moment a PI lands in their queue",
      "Allow approval from the mobile layout with a digital signature",
      "Escalate to the next level automatically when the SLA elapses",
    ],
  },

  /* ── 35 ─ PI Workflow Automation ───────────────────────────────────── */
  "workflow-automation": {
    name: "PI Workflow Automation", kind: "settings", summary: "Rules, triggers, routing and conditional workflow",
    entity: "Automation Rule", ref: "AUT",
    fields: [
      "ruleName|Rule|enum|Auto PI generation;Auto approval routing;Auto notification;Auto document generation;Auto email;Auto status update;Auto task creation;Auto reminder;Auto validation;Auto assignment",
      "trigger|Trigger|enum|On create;On submit;On approve;On reject;On due date;On SLA breach;Scheduled daily;API trigger",
      "condition|Conditional Workflow|text|Only when PI value is below 50000;Only for key account buyers;Only when validation passes clean;Only on LC backed PIs;Only outside the holiday calendar;No condition",
      "action|Action|enum|Generate PI;Route for approval;Notify;Send email;Generate document;Update status;Create task;Remind;Validate;Assign",
      "aiRule|AI Workflow Rule|bool|AI decides the route;Fixed rule",
      "threshold|Value Threshold|money|0;480000",
      "runs|Executions|int|0;980",
      "successRate|Success Rate|pct|58;100",
      "errors|Error Log Entries|int|0;140",
      "retries|Retry Attempts|int|0;8",
      "owner|Rule Owner|person",
      "date|Effective From|date|-600;60",
    ],
    statuses: ["Active", "Paused", "Draft", "Retrying", "Failed"],
    measure: "runs", rows: 48,
    settings: [
      "Auto-approve a PI below the threshold when validation passes clean",
      "Generate the commercial invoice and packing list automatically on approval",
      "Assign a new PI to the executive who owns that buyer",
      "Retry a failed automation three times before raising it in the error log",
      "Allow external systems to trigger a workflow through the API",
    ],
  },

  /* ── 36 ─ Workflow Monitoring Center ───────────────────────────────── */
  "workflow-monitoring": {
    name: "Workflow Monitoring Center", kind: "board", summary: "Live status, queues, SLA and user performance",
    entity: "Workflow Task", ref: "WFM",
    fields: [
      "taskType|Task|enum|PI approval;Data validation;Document upload;Buyer confirmation;Amendment review;Payment follow-up;Shipment booking;Automation run",
      PI_LINK,
      "assignee|Assigned To|person",
      "stage|Process Stage|enum|Created;Validated;Submitted;Under approval;Approved;Documented;Shipped;Closed",
      "queueDepth|Pending Tasks|int|0;48;tasks",
      "completedTasks|Completed Tasks|int|0;180;tasks",
      "delayedTasks|Delayed Tasks|int|0;24;tasks",
      "pendingHours|Pending For|float|0.5;720;hrs;1",
      "slaHours|SLA|int|4;168;hrs",
      "slaCompliance|SLA Compliance|pct|22;100",
      "userScore|User Performance|pct|28;100",
      "notificationState|Notification Status|enum|Delivered;Sent;Pending;Failed;Not applicable",
      "escalatedTo|Escalated To|person",
      "date|Raised On|date|-300;0",
    ],
    statuses: ["Completed", "In Progress", "Pending", "Delayed", "Escalated", "Failed"],
    measure: "pendingHours", rows: 64,
    insight: "Two users hold 44% of the open queue. Rebalancing on workload rather than on buyer ownership would clear the current backlog in about four working days.",
    settings: [
      "Show the live workflow status board on the commercial dashboard",
      "Alert the process owner as soon as a task passes 80% of its SLA",
      "Rebalance queues on workload rather than on buyer ownership",
    ],
  },

  /* ── 37 ─ PI Compliance Management ─────────────────────────────────── */
  "pi-compliance": {
    name: "PI Compliance Management", kind: "list", summary: "Export, buyer, country, document and quality checks",
    entity: "Compliance Check", ref: "CMP",
    fields: [
      PI_LINK, BUYER,
      "checkType|Compliance Rule|enum|Export compliance;Buyer compliance;Country compliance;Document compliance;Quality compliance;Shipment compliance;Payment compliance",
      COUNTRY, HS_CODE,
      "checklistDone|Compliance Checklist|pct|20;100",
      "score|Compliance Score|pct|38;100",
      "findings|Findings|int|0;12",
      "correctiveAction|Corrective Action|text|Attach the missing country certificate;Correct the HS code on the invoice;Obtain the nickel-free declaration;Reissue the packing list;Escalate to the compliance head;No action required",
      "alert|Compliance Alert|bool|Alert raised;No alert",
      "approver|Approved By|person",
      "checkedBy|Checked By|person",
      "archived|Archive|bool|Archived;Live",
      "date|Checked On|date|-330;0",
    ],
    statuses: ["Compliant", "Under Review", "Observation", "Corrective Action", "Waived", "Non-Compliant"],
    measure: "score", rows: 58,
    insight: "Every non-compliance this year traced back to one of two things: an HS code copied from an older item, or a country certificate that was never attached.",
    settings: [
      "Run the compliance checklist automatically before a PI is submitted",
      "Block export documentation while a non-compliance is open",
      "Notify the compliance head on every non-compliance the moment it is raised",
    ],
  },

  /* ── 38 ─ Risk Management ──────────────────────────────────────────── */
  "risk-management": {
    name: "Risk Management", kind: "analytics", summary: "Buyer, payment, shipment, currency and country risk",
    entity: "Risk Item", ref: "RSK",
    fields: [
      "riskType|Risk|enum|Buyer risk;Payment risk;Shipment risk;Currency risk;Compliance risk;Supplier risk;Country risk",
      BUYER, PI_LINK, COUNTRY,
      "assessment|Risk Assessment|enum|Annual review;PI level assessment;Event driven;AI generated;Ad hoc",
      "aiRiskScore|AI Risk Score|pct|4;98",
      "likelihood|Likelihood|enum|Very high;High;Medium;Low;Remote",
      "exposure|Exposure|money|2000;2400000",
      "correctiveAction|Corrective Action|text|Ask for a confirmed LC;Reduce the credit limit;Book earlier vessel space;Hedge the EUR exposure;Add third-party inspection;Require advance payment",
      "alert|Risk Alert|bool|Alert raised;No alert",
      "historyEntries|Risk History|int|1;24;entries",
      "approver|Approved By|person",
      "owner|Risk Owner|person",
      "archived|Archive|bool|Archived;Live",
      "date|Assessed On|date|-330;0",
    ],
    statuses: ["Mitigated", "Monitored", "High", "Critical", "Closed"],
    measure: "exposure", rows: 58,
    insight: "Payment risk concentrates in two buyers on open account terms — USD 640k of exposure carrying an AI risk score above 70 with no LC behind it.",
    settings: [
      "Score every new PI for buyer, payment and country risk on submission",
      "Require commercial head approval on any PI scoring above 70",
      "Alert the risk owner when exposure on one buyer passes their credit limit",
    ],
  },

  /* ── 39 ─ Reports & Analytics ──────────────────────────────────────── */
  "reports-analytics": {
    name: "Reports & Analytics", kind: "analytics", summary: "Dashboards, KPI, pivots, trends and drill-down",
    entity: "Report", ref: "RPT",
    fields: [
      "reportType|Report|enum|Dashboard report;Buyer report;PI report;Shipment report;LC report;Marketing report;Financial report;Performance report;Trend analysis;KPI report;Pivot report;Graphical report;Custom report",
      BUYER, CURRENCY, PERIOD,
      "records|Records|int|4;480",
      "value|Reported Value|money|8000;4800000",
      "analysis|Analysis Depth|enum|Summary;Drill down analysis;Pivot;AI analytics",
      "format|Output|enum|Dashboard chart;PDF export;Excel export;Scheduled email;Shared link",
      "sharedWith|Report Sharing|enum|Commercial team;Management;Finance;Buyer;Not shared",
      "archived|Report Archive|bool|Archived;Live",
      "generatedBy|Generated By|person",
      "date|Generated On|date|-330;0",
    ],
    statuses: ["Published", "Generated", "Scheduled", "Shared", "Archived", "Failed"],
    measure: "value", rows: 60,
    settings: [
      "Let any summary report drill down into the rows behind it",
      "Keep a dated copy of every scheduled report in the report archive",
      "Allow reports to be shared by link rather than as an attachment",
    ],
  },

  /* ── 40 ─ Financial Summary ────────────────────────────────────────── */
  "financial-summary": {
    name: "Financial Summary", kind: "analytics", summary: "Value, outstanding, receivable, cost, profit and margin",
    entity: "Financial Line", ref: "FIN",
    fields: [
      BUYER, CURRENCY, PERIOD,
      "piValue|PI Value Summary|money|4000;2400000",
      "shipmentValue|Shipment Value|money|0;2400000",
      "lcSummary|LC Summary|money|0;4800000",
      "receivable|Receivable Summary|money|0;2400000",
      "received|Payment Summary|money|0;2400000",
      "outstanding|Buyer Outstanding|money|0;1800000",
      "costTotal|Cost Summary|money|2000;1800000",
      "profit|Profit Summary|money|0;680000",
      "marginPct|Margin|pct|2;46",
      "cashFlow|Cash Flow|money|0;2400000",
      "trend|Trend|enum|Improving;Stable;Declining;Volatile",
      "summaryLevel|Summary Level|enum|Monthly summary;Yearly summary;Buyer summary;Currency summary",
      "date|Period End|date|-330;0",
    ],
    statuses: ["Settled", "Partially Received", "Outstanding", "Overdue", "Written Off"],
    measure: "piValue", rows: 60,
    insight: "Outstanding sits at 23% of PI value, but 61% of that is inside terms. The genuinely overdue portion is concentrated in one buyer and one shipping dispute.",
    settings: [
      "Report financial summaries in the base currency as well as the PI currency",
      "Treat receivable as overdue only after the agreed credit days have elapsed",
      "Publish the monthly and yearly summary to the board pack automatically",
    ],
  },

  /* ── 41 ─ KPI & Performance Dashboard ──────────────────────────────── */
  "kpi-performance": {
    name: "KPI & Performance Dashboard", kind: "overview", summary: "Targets, achievement, conversion and scorecards",
    entity: "KPI Record", ref: "KPI",
    fields: [
      "kpiName|KPI|enum|Commercial KPI;Buyer performance;Marketing performance;PI performance;Shipment performance;Approval performance;Revenue KPI;Profit KPI;Order conversion rate;Team performance;Department performance;Executive scorecard",
      BUYER, EXEC, PERIOD,
      "cadence|Cadence|enum|Monthly KPI;Quarterly KPI;Yearly KPI",
      "target|Target|money|40000;2400000",
      "actual|Achievement|money|0;2400000",
      "achievement|Target vs Achievement|pct|18;145",
      "conversionRate|Order Conversion Rate|pct|8;92",
      "revenue|Revenue|money|0;4800000",
      "profit|Profit|money|0;980000",
      "trend|Trend Analysis|enum|Improving;Stable;Declining;Volatile",
      "rank|Rank|int|1;24",
      "date|Period End|date|-330;0",
    ],
    statuses: ["Achieved", "On Track", "At Risk", "Missed"],
    measure: "actual", rows: 58,
    insight: "Approval turnaround is the only KPI moving the wrong way this quarter. Everything downstream of it — revenue timing, buyer satisfaction — follows that one number.",
    settings: [
      "Let each user choose which KPI widgets appear on their dashboard",
      "Compare every KPI against the same period last year as well as target",
      "Export the executive scorecard as a single-page PDF",
    ],
  },

  /* ── 42 ─ AI Intelligence & Recommendation ─────────────────────────── */
  "ai-intelligence": {
    name: "AI Intelligence & Recommendation", kind: "analytics", summary: "Price, cost, risk, approval and smart search",
    entity: "AI Insight", ref: "AII",
    fields: [
      "insightType|Insight|enum|AI commercial assistant;AI buyer recommendation;AI product recommendation;AI price recommendation;AI cost optimization;AI currency prediction;AI shipment recommendation;AI risk prediction;AI approval suggestion;AI smart notification;AI data analysis;AI duplicate detection;AI error detection;AI auto correction;AI smart search;AI decision support",
      BUYER, PI_LINK,
      "recommendation|Recommendation|text|Raise unit price by 5.2% on repeat items;Quantity looks 10x the buyer's usual break;Likely duplicate of PI-2026-000131;Buyer credit utilisation above 80%;Margin will fall below target at this price;Consolidate three PIs into one shipment;Hedge the EUR receivable book",
      "confidence|Confidence|pct|48;99.5",
      "impactValue|Value Impact|money|500;980000",
      "learningSignal|Learning Engine|enum|Accepted - model reinforced;Dismissed - model corrected;Awaiting feedback;Manually overridden",
      "acceptedBy|Actioned By|person",
      "date|Generated On|date|-300;0",
    ],
    statuses: ["Applied", "Accepted", "Reviewed", "New", "Dismissed"],
    measure: "impactValue", rows: 60,
    insight: "Accepted recommendations have moved USD 1.4M of PI value this year. Price suggestions carry the highest confidence; forecast insights carry the highest value but the widest error band.",
    settings: [
      "Surface AI recommendations inline on the PI entry form rather than in a separate queue",
      "Feed every accepted or dismissed recommendation back into the learning engine",
      "Require human confirmation before any AI auto-correction is written to a PI",
    ],
  },

  /* ── 43 ─ AI Business Intelligence Center ──────────────────────────── */
  "ai-business-intelligence": {
    name: "AI Business Intelligence Center", kind: "analytics", summary: "Executive BI, forecasting and decision support",
    entity: "BI Insight", ref: "BIC",
    fields: [
      "analysisType|Analysis|enum|Executive dashboard;Business intelligence;Sales analysis;Commercial analysis;Buyer analysis;Marketing analysis;Shipment analysis;Financial analysis;Trend analysis;Forecast analysis;AI predictive analytics",
      BUYER,
      "market|Market|enum|Europe;North America;Far East;Middle East;Australia;Local market",
      "horizon|Horizon|enum|Next month;Next quarter;Next six months;Next year",
      "forecastValue|Forecast Value|money|20000;4800000",
      "actualValue|Actual to Date|money|0;4800000",
      "confidence|Confidence|pct|48;99",
      "variance|Forecast Variance|pct|0;38",
      "visualisation|Data Visualization|enum|Trend line;Stacked bar;Heat map;Pareto;Scatter;Custom dashboard",
      "insightText|AI Insight|text|Add capacity for the Q3 European peak;Shift two buyers to LC terms;Raise prices on brass-heavy items;Open a second buying house in Vietnam;Consolidate low-value PIs;Hedge the EUR receivable book",
      "sharedWith|Dashboard Sharing|enum|Board pack;Commercial team;Management;Finance;Not shared",
      "owner|Owner|person",
      "date|Generated On|date|-330;0",
    ],
    statuses: ["Adopted", "Validated", "Monitoring", "New", "Rejected"],
    measure: "forecastValue", rows: 60,
    insight: "The twelve-month export forecast runs 8% above the order book already secured. History says roughly two thirds of that gap closes through repeat buyers placing late.",
    settings: [
      "Rebuild the forecast nightly from the live PI, shipment and payment data",
      "Let each executive pin their own widgets to a custom BI dashboard",
      "Show the confidence band alongside every forecast figure",
    ],
  },

  /* ── 44 ─ Integration Center ───────────────────────────────────────── */
  "integration-center": {
    name: "Integration Center", kind: "list", summary: "ERP, banking, EDI, portal, messaging and webhooks",
    entity: "Integration", ref: "INT",
    fields: [
      "system|System|enum|ERP integration;Accounting integration;Inventory integration;Production integration;CRM integration;HRMS integration;Banking integration;Email integration;SMS integration;WhatsApp integration;EDI integration;Buyer portal integration;Vendor portal integration;Mobile app integration;Third-party integration",
      "protocol|Protocol|enum|REST API;SOAP;EDI 850/810;SFTP;Webhook;Database link",
      "direction|Direction|enum|Inbound;Outbound;Bidirectional",
      "apiKey|API Management|enum|Key active;Key rotating;Key expired;OAuth token;No key required",
      "webhookUrl|Webhook|text|https://erp.internal/hooks/pi;https://bank.example/notify;https://portal.buyer.com/edi;Not configured",
      "recordsSynced|Records Synced|int|0;24000",
      "successRate|Success Rate|pct|52;100",
      "errors|Error Log Entries|int|0;140",
      "latencyMs|Latency|float|20;4800;ms;0",
      "syncHistory|Sync History Entries|int|1;480;runs",
      "lastSync|Last Sync|date|-30;0",
      "owner|Owner|person",
      "date|Connected On|date|-800;0",
    ],
    statuses: ["Connected", "Syncing", "Degraded", "Disconnected", "Error"],
    measure: "recordsSynced", rows: 52,
    settings: [
      "Retry a failed sync three times before marking the integration degraded",
      "Rotate API keys every 90 days and warn the owner two weeks ahead",
      "Push a webhook to the buyer portal whenever a PI is approved",
    ],
  },

  /* ── 45 ─ Multi-Company & Branch Management ────────────────────────── */
  "multi-company-branch": {
    name: "Multi-Company & Branch Management", kind: "list", summary: "Company, branch, factory and unit control",
    entity: "Company Unit", ref: "ORG",
    fields: [
      "company|Company Setup|enum|Smart Metal Accessories Ltd.;Smart Metal Export FZE;Smart Trims BD Ltd.;Smart Accessories Vietnam",
      "branch|Branch Setup|enum|Dhaka Head Office;Chattogram Branch;Dubai Office;Ho Chi Minh Office;Stockholm Liaison",
      "factory|Factory Setup|enum|Gazipur Plant;Sitakunda Plant;Narayanganj Unit;Ho Chi Minh Plant;Subcontract partner",
      "unit|Unit Setup|enum|Press unit;Plating unit;Assembly unit;Packing unit;Tooling unit",
      COUNTRY,
      "mapping|Branch Mapping|enum|Mapped to head office;Standalone;Reports to Chattogram;Reports to Dubai;Group level",
      "userAccess|User Company Access|int|2;68;users",
      "intercompany|Intercompany Transactions|money|0;1800000",
      "piCount|PI Count|int|1;180;PIs",
      "piValue|PI Value|money|8000;4800000",
      "dataSharing|Data Sharing|enum|Full group sharing;Masters shared only;Company isolated;Read-only across group",
      "logo|Company Logo|bool|Logo set;Using group logo",
      "documents|Company Documents|int|0;24;files",
      "approver|Approval by Company|person",
      "archived|Archive|bool|Archived;Live",
      "date|Active From|date|-1400;0",
    ],
    statuses: ["Active", "Setup", "Restricted", "Inactive", "Archived"],
    measure: "piValue", rows: 48,
    settings: [
      "Restrict a user to the PIs raised by their own company and branch",
      "Number PIs per company rather than across the whole group",
      "Share master data across the group but keep transactions company-isolated",
    ],
  },

  /* ── 46 ─ PI Template Management ───────────────────────────────────── */
  "pi-template": {
    name: "PI Template Management", kind: "settings", summary: "Layouts, logo, header, footer and dynamic fields",
    entity: "Template", ref: "TPL",
    fields: [
      "templateName|Template|enum|Standard export PI;Buyer branded PI;Compact PI;Detailed PI;LC submission PI;Multi-currency PI",
      BUYER,
      "layout|Template Layout|enum|Portrait;Landscape;Two column;Letterhead;Bank format",
      "printFormat|Print Format|enum|A4;A4 duplex;Letter;Legal;Continuous",
      "outputType|Output Template|enum|PDF template;Excel template;Email template;Print template",
      "logo|Company Logo|bool|Company logo;Buyer logo",
      "headerFooter|Header & Footer|text|Company letterhead with VAT BIN and ERC;Buyer address block with PO reference;Bank details in the footer;Terms block printed on page two;Signature and seal panel",
      "language|Language|enum|English;English and Bangla;English and German;English and Spanish;English and Japanese",
      "marks|Document Marks|enum|Watermark;QR code;Barcode;Digital signature;All marks;None",
      "dynamicFields|Dynamic Fields|int|4;64;fields",
      "version|Template Version|enum|V1;V2;V3;V4",
      "isDefault|Default Template|bool|Default;Alternate",
      "transfer|Import / Export|enum|Imported;Exported;Built in app;Copied from another template",
      "historyEntries|Template History|int|1;36;entries",
      "owner|Owner|person",
      "date|Updated On|date|-600;0",
    ],
    statuses: ["Active", "Draft", "Under Review", "Archived"],
    measure: "dynamicFields", rows: 46,
    settings: [
      "Fall back to the company default template when a buyer has none set",
      "Lock a template version once a PI has been printed from it",
      "Preview a template against a real PI before it is made active",
    ],
  },

  /* ── 47 ─ Security & Access Control ────────────────────────────────── */
  "security-access-control": {
    name: "Security & Access Control", kind: "settings", summary: "Users, roles, permissions, 2FA and sessions",
    entity: "Access Rule", ref: "SEC",
    fields: [
      "user|User|person",
      "role|Role|enum|Merchandiser;Marketing Manager;Commercial Head;Finance Officer;Administrator;Auditor;Read-only",
      "scope|Permission Scope|enum|Menu permission;Button permission;Field permission;Data access control;Approval permission;Branch wise access;Company wise access",
      "permission|Permission|enum|View;Create;Edit;Approve;Print;Export;Delete;Full control",
      "passwordPolicy|Password Policy|enum|12 characters with rotation;8 characters minimum;Complex with history;SSO managed;Default policy",
      "twoFactor|Two Factor Authentication|bool|Enabled;Disabled",
      "ipRestriction|IP Restriction|enum|No restriction;Office network only;VPN only;Whitelisted IPs;Country locked",
      "device|Device Management|enum|Registered desktop;Registered mobile;Any device;Managed device only",
      "sessions|Active Sessions|int|0;12;sessions",
      "loginCount|Login History|int|0;480;logins",
      "securityEvents|Security Log Entries|int|0;140",
      "auditEntries|Audit Trail Entries|int|0;480",
      "lastLogin|Last Login|date|-90;0",
      "date|Granted On|date|-700;0",
    ],
    statuses: ["Active", "Pending Approval", "Suspended", "Revoked"],
    measure: "securityEvents", rows: 56,
    settings: [
      "Require two-factor authentication for anyone with approval rights",
      "Deny access from outside the office network for delete and export actions",
      "Expire an idle session after 30 minutes and force a fresh sign-in",
      "Write every permission change to the security log and the audit trail",
    ],
  },

  /* ── 48 ─ Audit Trail & Activity Log ───────────────────────────────── */
  "audit-trail": {
    name: "Audit Trail & Activity Log", kind: "list", summary: "Who did what, from where, on which record",
    entity: "Audit Entry", ref: "AUD",
    fields: [
      "user|User|person",
      "action|Action|enum|Login;Logout;Create;Update;Delete;Approve;Print;Export;Email;File upload;API call;System activity",
      PI_LINK,
      "screen|Screen|enum|PI Entry;PI Register;Approval Workflow;Buyer Management;Price & Costing;Documents;Reports;System Settings",
      "detail|Detail|text|Changed unit price from 0.5800 to 0.6100;Approved at commercial head level;Exported 68 rows to Excel;Uploaded LC-2026-4471.pdf;Deleted a draft PI;Signed in from a new device",
      "ipAddress|IP Address|enum|103.108.140.22;103.108.140.31;115.127.24.9;180.211.137.4;27.147.155.18;192.168.10.42",
      "device|Device|enum|Windows desktop;MacBook Pro;Android phone;iPhone;iPad;Linux workstation",
      "errorLog|Error Log|text|No error;Permission denied;Session expired;API timeout;File too large;Validation failed",
      "sessionMin|Session Length|float|0.2;240;min;1",
      "archived|Archive|bool|Archived;Live",
      "date|Timestamp|date|-300;0",
    ],
    statuses: ["Success", "Flagged", "Failed", "Blocked"],
    measure: "sessionMin", rows: 76,
    insight: "Every create, update, delete, approval, print and download is written with the user, IP and device attached — the trail is append-only, so the log itself cannot be edited from the screen.",
    settings: [
      "Keep the audit trail append-only — no edit or delete from any screen",
      "Retain audit entries for seven years before archiving them",
      "Alert the administrator on any blocked or flagged activity",
    ],
  },

  /* ── 49 ─ System Utilities ─────────────────────────────────────────── */
  "system-utilities": {
    name: "System Utilities", kind: "settings", summary: "Numbering, configuration, scheduler and health",
    entity: "Utility", ref: "UTL",
    fields: [
      "utility|Utility|enum|System configuration;Number series setup;Auto numbering;Email configuration;SMS configuration;Notification settings;Language settings;Currency settings;Date format;Time zone;Backup settings;Restore settings;Import data;Export data;Scheduler;Cache management;System health;License management;System logs;Maintenance mode",
      "seriesPrefix|Number Series|enum|PI-2026-;LC-2026-;INV-2026-;FIL-26-;SHP-26-;AMD-26-",
      "nextNumber|Next Number|int|1;9000",
      "language|Language|enum|English;Bangla;German;Spanish;Japanese;Chinese",
      "dateFormat|Date Format|enum|DD MMM YYYY;DD/MM/YYYY;MM/DD/YYYY;YYYY-MM-DD",
      "timeZone|Time Zone|enum|Asia/Dhaka;Asia/Ho_Chi_Minh;Europe/Berlin;Europe/London;America/New_York;UTC",
      "baseCurrency|Currency Setting|enum|USD;BDT;EUR;GBP",
      "scheduler|Scheduler|enum|Hourly;Daily 02:00;Weekly Sunday;Monthly;On demand;Disabled",
      "cacheMb|Cache Size|float|2;980;MB;1",
      "healthScore|System Health|pct|42;100",
      "licenseSeats|License Seats|int|5;250;seats",
      "logEntries|System Log Entries|int|0;4800",
      "maintenance|Maintenance Mode|bool|Maintenance on;Live",
      "owner|Owner|person",
      "date|Updated On|date|-500;0",
    ],
    statuses: ["Applied", "Scheduled", "Pending", "Failed"],
    measure: "logEntries", rows: 50,
    settings: [
      "Generate every document number from its series rather than by hand",
      "Clear the report cache nightly and rebuild it before the working day",
      "Warn 30 days before the license expires or the seat count is reached",
      "Put the system into maintenance mode during a restore rather than blocking users at random",
    ],
  },

  /* ── 50 ─ Data Backup & Recovery ───────────────────────────────────── */
  "backup-recovery": {
    name: "Data Backup & Recovery", kind: "list", summary: "Backups, schedules, restore and disaster recovery",
    entity: "Backup Job", ref: "BKP",
    fields: [
      "backupType|Backup Type|enum|Manual backup;Auto backup;Scheduled backup;Full backup;Incremental backup;Database backup;File backup;Cloud backup",
      "destination|Destination|enum|On-premise NAS;AWS S3;Azure Blob;Google Cloud Storage;Offsite tape;Secondary data centre",
      "schedule|Schedule|enum|Hourly;Daily 02:00;Weekly Sunday;Monthly;On demand",
      "sizeGb|Size|float|0.2;480;GB;2",
      "durationMin|Duration|float|0.5;240;min;1",
      "encrypted|Backup Encryption|bool|AES-256 encrypted;Not encrypted",
      "verified|Backup Verification|bool|Checksum verified;Not verified",
      "restoreType|Restore|enum|Restore database;Restore files;Full disaster recovery;Point in time;Not restored",
      "restoreTested|Restore Tested|bool|Restore verified;Not tested",
      "recoveryLogs|Recovery History Entries|int|0;48",
      "downloadable|Download Backup|bool|Available to download;Archive only",
      "failureAlert|Failure Alert|bool|Alert raised;No alert",
      "retentionDays|Retention|int|7;730;days",
      "owner|Owner|person",
      "date|Run On|date|-200;0",
    ],
    statuses: ["Completed", "Running", "Scheduled", "Restored", "Failed"],
    measure: "sizeGb", rows: 56,
    settings: [
      "Run an automatic encrypted cloud backup every night and verify the checksum",
      "Test a restore from the most recent backup once a month",
      "Alert the administrator immediately on any backup failure",
      "Keep a full backup weekly and incremental backups in between",
    ],
  },

  /* ── 51 ─ System Settings ──────────────────────────────────────────── */
  "system-settings": {
    name: "System Settings", kind: "settings", summary: "General, PI, AI, workflow, print and security settings",
    entity: "Setting", ref: "SET",
    fields: [
      "settingGroup|Setting Group|enum|General settings;Commercial settings;PI settings;AI settings;Approval settings;Workflow settings;Print settings;Email settings;Notification settings;User preferences;Dashboard preferences;Theme settings;Company preferences;Integration settings;Security settings;Backup settings;System parameters;Default values;Environment settings;System initialization",
      "settingName|Setting|text|Default PI validity days;Default currency;Auto approval threshold;AI confidence floor;Print template default;Email sender address;Session timeout minutes;Dashboard refresh interval;Theme mode;Backup retention days",
      "currentValue|Current Value|text|30 days;USD;50000;90%;Standard export PI;commercial@smartmetal.com;30 minutes;5 minutes;System theme;365 days",
      "defaultValue|Default Value|text|30 days;USD;0;95%;Standard export PI;noreply@smartmetal.com;60 minutes;10 minutes;Light;180 days",
      "scope|Scope|enum|System wide;Company;Branch;Role;User preference",
      "environment|Environment|enum|Production;Staging;Test;Development",
      "restartRequired|Restart Required|bool|Restart required;Applies immediately",
      "changes|Change History|int|1;48;changes",
      "owner|Changed By|person",
      "date|Updated On|date|-500;0",
    ],
    statuses: ["Applied", "Pending Restart", "Default", "Overridden"],
    measure: "changes", rows: 52,
    settings: [
      "Let a user override a system default only where the setting allows it",
      "Show the shipped default alongside the current value on every setting",
      "Require administrator rights to change any security or integration setting",
      "Keep a dated history of every settings change in the audit trail",
    ],
  },
};
